// ============================================================
// Grocery Commerce — Export Utilities
// Copy, PDF, email, native share for global fallback
// ============================================================

import type { GroceryList, GroceryLine } from '@/lib/planner/types'
import { GROCERY_ICONS, CATEGORY_ORDER } from '@/lib/planner/types'

/**
 * Format grocery list as plain text (for copy/share).
 */
export function formatGroceryListAsText(groceryList: GroceryList): string {
  const lines: string[] = []
  lines.push('🛒 MealEase Grocery List')
  lines.push(`Week of ${groceryList.weekStart}`)
  lines.push(`${groceryList.items.filter((i) => !i.isInPantry).length} items to buy`)
  lines.push('')

  // Group by category
  const grouped = groupByCategory(groceryList.items.filter((i) => !i.isInPantry && !i.isChecked))

  for (const [category, items] of grouped) {
    const icon = GROCERY_ICONS[category] ?? '🛒'
    lines.push(`${icon} ${category.charAt(0).toUpperCase() + category.slice(1)}`)
    lines.push('─'.repeat(30))
    for (const item of items) {
      const qty = item.quantity % 1 === 0 ? String(item.quantity) : item.quantity.toFixed(1)
      const cost = item.estimatedCost > 0 ? ` (~$${item.estimatedCost.toFixed(2)})` : ''
      lines.push(`  □ ${item.name} — ${qty} ${item.unit}${cost}`)
      if (item.note) lines.push(`    📝 ${item.note}`)
    }
    lines.push('')
  }

  const total = groceryList.totalEstimatedCost
  if (total > 0) {
    lines.push(`💰 Estimated total: $${total.toFixed(2)}`)
  }
  lines.push('')
  lines.push('Generated by MealEase — mealease.co')

  return lines.join('\n')
}

/**
 * Format grocery list as HTML (for PDF/email).
 */
export function formatGroceryListAsHTML(groceryList: GroceryList): string {
  const grouped = groupByCategory(groceryList.items.filter((i) => !i.isInPantry && !i.isChecked))

  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>MealEase Grocery List — Week of ${groceryList.weekStart}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 32px; max-width: 600px; margin: 0 auto; color: #1a1a1a; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
    .category { margin-bottom: 20px; }
    .category-header { font-size: 16px; font-weight: 700; padding: 8px 0; border-bottom: 2px solid #f0f0f0; margin-bottom: 8px; }
    .item { display: flex; align-items: flex-start; gap: 8px; padding: 6px 0; }
    .checkbox { width: 16px; height: 16px; border: 2px solid #ccc; border-radius: 3px; flex-shrink: 0; margin-top: 2px; }
    .item-name { font-size: 14px; font-weight: 500; }
    .item-qty { font-size: 12px; color: #666; }
    .item-cost { font-size: 12px; color: #888; margin-left: auto; }
    .item-note { font-size: 11px; color: #7c3aed; font-style: italic; margin-left: 24px; }
    .total { margin-top: 24px; padding-top: 16px; border-top: 2px solid #f0f0f0; font-size: 18px; font-weight: 700; }
    .footer { margin-top: 32px; font-size: 11px; color: #999; text-align: center; }
  </style>
</head>
<body>
  <h1>🛒 Grocery List</h1>
  <p class="subtitle">Week of ${groceryList.weekStart} · ${groceryList.items.filter((i) => !i.isInPantry).length} items</p>
`

  for (const [category, items] of grouped) {
    const icon = GROCERY_ICONS[category] ?? '🛒'
    html += `  <div class="category">
    <div class="category-header">${icon} ${category.charAt(0).toUpperCase() + category.slice(1)}</div>
`
    for (const item of items) {
      const qty = item.quantity % 1 === 0 ? String(item.quantity) : item.quantity.toFixed(1)
      const cost = item.estimatedCost > 0 ? `<span class="item-cost">~$${item.estimatedCost.toFixed(2)}</span>` : ''
      html += `    <div class="item">
      <div class="checkbox"></div>
      <div>
        <span class="item-name">${escapeHtml(item.name)}</span>
        <span class="item-qty"> — ${qty} ${escapeHtml(item.unit)}</span>
      </div>
      ${cost}
    </div>
`
      if (item.note) {
        html += `    <div class="item-note">📝 ${escapeHtml(item.note)}</div>\n`
      }
    }
    html += `  </div>\n`
  }

  const total = groceryList.totalEstimatedCost
  if (total > 0) {
    html += `  <div class="total">💰 Estimated total: $${total.toFixed(2)}</div>\n`
  }

  html += `  <div class="footer">Generated by MealEase — mealease.co</div>
</body>
</html>`

  return html
}

/**
 * Copy grocery list to clipboard as plain text.
 */
export async function copyGroceryList(groceryList: GroceryList): Promise<boolean> {
  try {
    const text = formatGroceryListAsText(groceryList)
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    // Fallback for older browsers
    try {
      const text = formatGroceryListAsText(groceryList)
      const textarea = document.createElement('textarea')
      textarea.value = text
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      return true
    } catch {
      return false
    }
  }
}

/**
 * Download grocery list as PDF (using print-to-PDF via new window).
 */
export function downloadGroceryListPDF(groceryList: GroceryList): void {
  const html = formatGroceryListAsHTML(groceryList)
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)

  const printWindow = window.open(url, '_blank')
  if (printWindow) {
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print()
        URL.revokeObjectURL(url)
      }, 250)
    }
  } else {
    // Fallback: download as HTML file
    const a = document.createElement('a')
    a.href = url
    a.download = `mealease-grocery-${groceryList.weekStart}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }
}

/**
 * Share grocery list via native Web Share API.
 */
export async function shareGroceryList(groceryList: GroceryList): Promise<boolean> {
  const text = formatGroceryListAsText(groceryList)

  if (typeof navigator !== 'undefined' && navigator.share) {
    try {
      await navigator.share({
        title: `MealEase Grocery List — Week of ${groceryList.weekStart}`,
        text,
      })
      return true
    } catch {
      // User cancelled or share failed
      return false
    }
  }

  // Fallback to copy
  return copyGroceryList(groceryList)
}

/**
 * Generate mailto link for emailing grocery list.
 */
export function getEmailGroceryListUrl(groceryList: GroceryList): string {
  const subject = encodeURIComponent(`MealEase Grocery List — Week of ${groceryList.weekStart}`)
  const body = encodeURIComponent(formatGroceryListAsText(groceryList))
  return `mailto:?subject=${subject}&body=${body}`
}

// ── Helpers ──────────────────────────────────────────────────

function groupByCategory(items: GroceryLine[]): [string, GroceryLine[]][] {
  const map = new Map<string, GroceryLine[]>()
  for (const item of items) {
    if (!map.has(item.category)) map.set(item.category, [])
    map.get(item.category)!.push(item)
  }

  // Sort by CATEGORY_ORDER
  const sorted: [string, GroceryLine[]][] = []
  for (const cat of CATEGORY_ORDER) {
    if (map.has(cat)) {
      sorted.push([cat, map.get(cat)!])
      map.delete(cat)
    }
  }
  // Append remaining categories
  for (const [cat, items] of map) {
    sorted.push([cat, items])
  }
  return sorted
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
