// ============================================================
// Smart Meal Engine — Curated Meal Database
// ============================================================

import type { MealCandidate, MealIngredient, MealVariationData, IngredientCategory } from './types'
import { MEALS_EXTENDED } from './meals-extended'
import { MEALS_NEPALI } from './meals-nepali'

// ── Helpers ──────────────────────────────────────────────────

export function ing(
  name: string,
  qty: string,
  unit: string,
  cat: IngredientCategory,
  staple = false,
  note?: string,
): MealIngredient {
  return { name, quantity: qty, unit, category: cat, pantryStaple: staple, ...(note ? { note } : {}) }
}

export function v(
  title: string,
  desc: string,
  mods: string[],
  safety: string[],
  texture: string | null,
  tip: string,
): MealVariationData {
  return { title, description: desc, modifications: mods, safetyNotes: safety, textureNotes: texture, servingTip: tip }
}

// ── Meal Database ───────────────────────────────────────────

export const MEAL_DATABASE: MealCandidate[] = [
  // ─── 1. Creamy Tomato Pasta ───────────────────────────────
  {
    id: 'creamy-tomato-pasta',
    title: 'Creamy Tomato Pasta',
    tagline: 'A 20-minute pantry hero the whole family loves',
    description: 'Penne tossed in a velvety tomato-cream sauce with garlic and basil. Simple, comforting, and endlessly adaptable for every eater at the table.',
    cuisineTags: ['italian', 'comfort'],
    proteinType: 'none',
    prepTime: 5,
    cookTime: 15,
    estimatedCost: 8,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['one-pot', 'vegetarian', 'quick', 'pantry-friendly', 'kid-favorite'],
    kidFriendlyScore: 10,
    dietaryCompat: ['vegetarian', 'nut-free'],
    ingredients: [
      ing('penne pasta', '12', 'oz', 'grain', true),
      ing('canned crushed tomatoes', '1', 'can (28 oz)', 'pantry_staple', true),
      ing('heavy cream', '1/2', 'cup', 'dairy'),
      ing('garlic', '3', 'cloves', 'produce'),
      ing('olive oil', '2', 'tbsp', 'pantry_staple', true),
      ing('dried basil', '1', 'tsp', 'spice', true),
      ing('dried oregano', '1/2', 'tsp', 'spice', true),
      ing('parmesan cheese', '1/4', 'cup', 'dairy', false, 'grated'),
      ing('salt', '', 'to taste', 'spice', true),
      ing('black pepper', '', 'to taste', 'spice', true),
    ],
    steps: [
      'Cook pasta according to package directions; drain and reserve 1/2 cup pasta water.',
      'In the same pot, heat olive oil over medium heat. Sauté minced garlic for 30 seconds until fragrant.',
      'Add crushed tomatoes, basil, and oregano. Simmer for 8 minutes, stirring occasionally.',
      'Stir in heavy cream and simmer 2 more minutes until sauce is smooth and slightly thickened.',
      'Toss pasta into the sauce; add pasta water a splash at a time to reach desired consistency.',
      'Serve topped with grated parmesan.',
    ],
    variations: {
      adult: v(
        'Creamy Tomato Pasta',
        'Full-flavored with fresh cracked pepper and extra parmesan',
        ['Add red pepper flakes for heat', 'Top with fresh basil and extra parmesan', 'Optional: stir in sun-dried tomatoes'],
        [], null,
        'Pair with garlic bread and a green salad',
      ),
      kid: v(
        'Creamy Pink Pasta',
        'Mild, smooth sauce that kids go crazy for',
        ['Skip pepper flakes', 'Extra parmesan stirred in for creaminess', 'Fun pasta shapes if available'],
        [], null,
        'Serve with cucumber slices for crunch',
      ),
      toddler: v(
        'Mini Pink Pasta Bites',
        'Soft small pasta in smooth tomato cream',
        ['Use small pasta shapes (ditalini or mini penne)', 'Blend sauce until very smooth', 'Skip salt and pepper', 'Cool to safe temperature'],
        ['Cut long pasta into small pieces', 'Test temperature before serving'],
        'Soft, smooth sauce with no chunks — pasta should be well-cooked',
        'Let them self-feed with a spoon for fine motor practice',
      ),
      baby: v(
        'Tomato Cream Pasta Purée',
        'Smooth, iron-rich tomato sauce over mashed soft pasta',
        ['Blend sauce completely smooth', 'Overcook a small portion of pasta until very soft', 'Mash pasta with a fork', 'No salt, no sugar, no honey', 'Skip parmesan if under 12 months'],
        ['No honey', 'No added salt or sugar', 'Check for dairy allergy before serving', 'Supervise all eating'],
        'Completely smooth purée for 6-8mo, soft mashed pieces for 9-12mo',
        'Offer on a preloaded spoon or spread on a silicone mat',
      ),
    },
    simplifiedSteps: [
      'Cook pasta. While it drains, heat jarred marinara in the same pot.',
      'Stir in cream and garlic powder. Toss with pasta.',
      'Top with parmesan and serve.',
    ],
    simplifiedSwaps: [
      { from: 'garlic', to: 'garlic powder (1/2 tsp)' },
      { from: 'canned crushed tomatoes', to: 'jarred marinara (2 cups)' },
    ],
    leftoverTip: 'Stores 3 days. Reheat with a splash of milk to restore creaminess.',
    keyIngredients: ['pasta', 'tomatoes', 'cream', 'garlic', 'parmesan'],
    relatedTerms: ['pasta', 'tomato pasta', 'creamy pasta', 'pink sauce', 'penne', 'marinara', 'red sauce pasta', 'spaghetti'],
  },

  // ─── 2. Beef Taco Bowl ────────────────────────────────────
  {
    id: 'beef-taco-bowl',
    title: 'Beef Taco Bowl',
    tagline: 'Deconstructed tacos everyone can customize',
    description: 'Seasoned ground beef over rice with all the fixings — cheese, salsa, avocado, and sour cream. Easy to build and easy to adapt for every age.',
    cuisineTags: ['mexican', 'comfort'],
    proteinType: 'beef',
    prepTime: 10,
    cookTime: 15,
    estimatedCost: 12,
    costLevel: 'medium',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['one-pan', 'customizable', 'kid-friendly', 'quick'],
    kidFriendlyScore: 9,
    dietaryCompat: ['nut-free', 'gluten-free'],
    ingredients: [
      ing('ground beef', '1', 'lb', 'protein', false, '85/15'),
      ing('white rice', '1.5', 'cups', 'grain', true),
      ing('canned black beans', '1', 'can (15 oz)', 'pantry_staple', true, 'drained & rinsed'),
      ing('cheddar cheese', '1', 'cup', 'dairy', false, 'shredded'),
      ing('salsa', '1/2', 'cup', 'condiment', true),
      ing('sour cream', '1/4', 'cup', 'dairy'),
      ing('avocado', '1', 'medium', 'produce'),
      ing('chili powder', '1', 'tbsp', 'spice', true),
      ing('cumin', '1', 'tsp', 'spice', true),
      ing('garlic powder', '1/2', 'tsp', 'spice', true),
      ing('olive oil', '1', 'tbsp', 'pantry_staple', true),
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat olive oil in a large skillet over medium-high heat. Add ground beef and break into crumbles.',
      'Cook beef 6-7 minutes until browned. Drain excess fat.',
      'Add chili powder, cumin, garlic powder, and 2 tbsp water. Stir and cook 2 minutes.',
      'Assemble bowls: rice base, seasoned beef, black beans, cheese, salsa, avocado, sour cream.',
    ],
    variations: {
      adult: v(
        'Loaded Taco Bowl',
        'Full-flavored bowl with all the toppings and hot sauce',
        ['Add pickled jalapeños or hot sauce', 'Extra avocado and fresh cilantro', 'Squeeze of lime juice'],
        [], null,
        'Top with a fried egg for extra protein',
      ),
      kid: v(
        'Taco Rice Bowl',
        'Mild seasoned beef with cheese and favorite toppings',
        ['Use half the chili powder for milder flavor', 'Let them pick their own toppings', 'Shredded cheese on top'],
        [], null,
        'Serve with tortilla chips on the side for dipping',
      ),
      toddler: v(
        'Baby Taco Bowl',
        'Soft, mildly seasoned beef with mashed beans and rice',
        ['Skip all spices or use just a pinch of cumin', 'Mash black beans with a fork', 'Rice should be well-cooked and soft', 'Cut avocado into thin strips', 'No salt added'],
        ['Ensure beef is in small, soft crumbles', 'Avocado strips prevent choking vs chunks', 'Test temperature'],
        'Soft, mashable textures — no crunchy toppings',
        'Serve in a suction bowl and let them explore with hands',
      ),
      baby: v(
        'Taco Beef Mash',
        'Plain ground beef with mashed beans and soft avocado',
        ['Plain unseasoned ground beef (cook a small portion separately)', 'Mash beans until smooth', 'Mash avocado smooth', 'Mix with well-cooked rice', 'No salt, no spices, no cheese if under 12mo'],
        ['No honey', 'No added salt or seasonings', 'No whole beans (choking hazard)', 'Supervise all eating'],
        'Smooth mash for 6-8mo, soft lumpy mash for 9-12mo',
        'Offer mashed avocado on a preloaded spoon as a first taste',
      ),
    },
    simplifiedSteps: [
      'Cook instant rice. Brown ground beef in a skillet, drain fat.',
      'Stir in taco seasoning packet with 2 tbsp water.',
      'Assemble bowls with rice, beef, canned beans, cheese, and salsa.',
    ],
    simplifiedSwaps: [
      { from: 'chili powder + cumin + garlic powder', to: 'store-bought taco seasoning packet' },
    ],
    leftoverTip: 'Keep components separate for next-day bowls. Beef + beans reheat well for 3 days.',
    keyIngredients: ['ground beef', 'rice', 'black beans', 'cheese', 'avocado', 'salsa'],
    relatedTerms: ['taco', 'taco bowl', 'burrito bowl', 'mexican bowl', 'ground beef', 'beef tacos', 'tex-mex'],
  },

  // ─── 3. Teriyaki Salmon with Rice ────────────────────────
  {
    id: 'teriyaki-salmon-rice',
    title: 'Teriyaki Salmon with Rice',
    tagline: 'Restaurant-quality salmon in under 25 minutes',
    description: 'Flaky pan-seared salmon glazed with a sweet-savory teriyaki sauce, served over steamed rice with sautéed broccoli.',
    cuisineTags: ['asian'],
    proteinType: 'fish',
    prepTime: 5,
    cookTime: 18,
    estimatedCost: 16,
    costLevel: 'high',
    servings: 4,
    difficulty: 'moderate',
    energyDemand: 'medium',
    tags: ['high-protein', 'omega-3', 'healthy', 'date-night-worthy'],
    kidFriendlyScore: 6,
    dietaryCompat: ['nut-free', 'dairy-free', 'gluten-free'],
    ingredients: [
      ing('salmon fillets', '4', 'pieces (6 oz each)', 'protein'),
      ing('white rice', '1.5', 'cups', 'grain', true),
      ing('soy sauce', '3', 'tbsp', 'condiment', true),
      ing('honey', '2', 'tbsp', 'pantry_staple', true),
      ing('rice vinegar', '1', 'tbsp', 'condiment', true),
      ing('sesame oil', '1', 'tsp', 'condiment', true),
      ing('garlic', '2', 'cloves', 'produce'),
      ing('fresh ginger', '1', 'tsp', 'produce', false, 'grated'),
      ing('broccoli florets', '3', 'cups', 'produce'),
      ing('sesame seeds', '1', 'tbsp', 'spice', true, 'for garnish'),
      ing('scallion', '2', 'stalks', 'produce', false, 'sliced'),
      ing('vegetable oil', '2', 'tbsp', 'pantry_staple', true),
    ],
    steps: [
      'Cook rice according to package directions.',
      'Whisk soy sauce, honey, rice vinegar, sesame oil, minced garlic, and ginger in a small bowl.',
      'Heat 1 tbsp oil in a large skillet over medium-high heat. Pat salmon dry and place skin-side up.',
      'Sear 4 minutes until golden. Flip and cook 3 more minutes.',
      'Pour teriyaki sauce over salmon. Reduce heat and let glaze thicken 2 minutes, spooning sauce over fish.',
      'In a separate pan, sauté broccoli in remaining oil for 3-4 minutes until bright green and tender-crisp.',
      'Serve salmon over rice with broccoli. Garnish with sesame seeds and scallions.',
    ],
    variations: {
      adult: v(
        'Teriyaki Glazed Salmon',
        'Rich, caramelized teriyaki glaze with sesame and scallion',
        ['Extra glaze spooned over top', 'Sprinkle with toasted sesame seeds', 'Add sriracha drizzle for heat'],
        [], null,
        'Pair with a cold cucumber salad',
      ),
      kid: v(
        'Sweet Salmon Bites',
        'Mild, sweet-glazed salmon pieces kids actually like',
        ['Cut salmon into bite-sized pieces after cooking', 'The sweet teriyaki glaze helps fish-hesitant kids', 'Serve broccoli as "tiny trees"'],
        ['Check for small bones before serving'], null,
        'Dip salmon pieces in extra teriyaki sauce for fun',
      ),
      toddler: v(
        'Soft Salmon Flakes',
        'Tender, flaked salmon with soft steamed broccoli',
        ['Flake salmon into small, soft pieces', 'Steam broccoli until very soft', 'Use only a tiny drizzle of sauce (low sodium)', 'Mash rice slightly for easier eating', 'No added salt'],
        ['Remove all bones carefully', 'Test temperature', 'Cut broccoli heads into tiny pieces'],
        'Very soft, flaked fish — no crispy skin. Broccoli steamed until easily squished.',
        'Let them pick up flaked salmon pieces with fingers',
      ),
      baby: v(
        'Salmon Rice Mash',
        'Omega-3-rich mashed salmon with soft rice',
        ['Cook a small unseasoned salmon portion (no soy, no honey)', 'Mash thoroughly with well-cooked rice', 'Steam broccoli very soft and mash', 'No salt, no honey, no soy sauce'],
        ['No honey (botulism risk under 1 year)', 'No soy sauce (too much sodium)', 'No added salt', 'Remove every bone', 'Supervise all eating'],
        'Smooth mash for 6-8mo, soft flakes for 9-12mo',
        'Salmon is an excellent first protein — offer plain flakes on a preloaded spoon',
      ),
    },
    simplifiedSteps: [
      'Cook rice. Pan-sear salmon fillets 4 min per side.',
      'Drizzle with store-bought teriyaki sauce. Steam broccoli in microwave.',
      'Plate and serve.',
    ],
    simplifiedSwaps: [
      { from: 'soy sauce + honey + rice vinegar + sesame oil + garlic + ginger', to: 'store-bought teriyaki sauce (1/3 cup)' },
    ],
    leftoverTip: 'Leftover salmon makes great next-day rice bowls or salmon salad.',
    keyIngredients: ['salmon', 'rice', 'soy sauce', 'honey', 'broccoli', 'ginger'],
    relatedTerms: ['salmon', 'teriyaki', 'fish', 'salmon rice', 'teriyaki salmon', 'glazed salmon', 'seared salmon'],
  },

  // ─── 4. Sheet Pan Sausage & Roasted Veggies ──────────────
  {
    id: 'sheet-pan-sausage-veg',
    title: 'Sheet Pan Sausage & Roasted Veggies',
    tagline: 'Dump it on a pan. Walk away. Dinner done.',
    description: 'Sliced sausage with potatoes, bell peppers, and broccoli all roasted on one sheet pan. Minimal prep, zero active cooking, easy clean-up.',
    cuisineTags: ['american', 'comfort'],
    proteinType: 'sausage',
    prepTime: 8,
    cookTime: 25,
    estimatedCost: 10,
    costLevel: 'medium',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['sheet-pan', 'low-effort', 'one-pan', 'meal-prep-friendly'],
    kidFriendlyScore: 7,
    dietaryCompat: ['nut-free', 'dairy-free', 'gluten-free'],
    ingredients: [
      ing('smoked sausage', '14', 'oz', 'protein', false, 'sliced into coins'),
      ing('baby potatoes', '1', 'lb', 'produce', false, 'halved'),
      ing('bell peppers', '2', 'medium', 'produce', false, 'chopped'),
      ing('broccoli florets', '2', 'cups', 'produce'),
      ing('olive oil', '3', 'tbsp', 'pantry_staple', true),
      ing('garlic powder', '1', 'tsp', 'spice', true),
      ing('smoked paprika', '1', 'tsp', 'spice', true),
      ing('salt', '1/2', 'tsp', 'spice', true),
      ing('black pepper', '1/4', 'tsp', 'spice', true),
    ],
    steps: [
      'Preheat oven to 425°F (220°C). Line a large sheet pan with parchment.',
      'Toss halved potatoes with 1 tbsp olive oil, garlic powder, paprika, salt, and pepper. Spread on pan.',
      'Roast potatoes alone for 10 minutes to give them a head start.',
      'Add sausage coins, bell peppers, and broccoli to the pan. Drizzle with remaining olive oil and toss.',
      'Return to oven and roast 15 more minutes until sausage is browned and veggies are tender.',
      'Serve straight from the pan.',
    ],
    variations: {
      adult: v(
        'Sheet Pan Sausage & Veggies',
        'Savory roasted sausage with caramelized vegetables',
        ['Add a drizzle of balsamic glaze', 'Toss in red onion wedges', 'Serve with whole grain mustard'],
        [], null,
        'Great with crusty bread to soak up the pan juices',
      ),
      kid: v(
        'Sausage Coins & Roasted Potatoes',
        'Fun coin-shaped sausage with soft roasted potatoes',
        ['Kids love the sausage coin shape', 'Keep bell pepper pieces large enough to pick around if needed', 'Offer ketchup for dipping'],
        [], null,
        'Let them dip sausage coins in ketchup or mustard',
      ),
      toddler: v(
        'Soft Sausage & Potato Bites',
        'Tender sausage pieces with very soft roasted veggies',
        ['Cut sausage into small quarters (not rounds — choking hazard)', 'Ensure potatoes are fork-tender', 'Steam broccoli extra soft separately', 'Skip salt and paprika for their portion'],
        ['Cut sausage lengthwise then into small pieces', 'Ensure potatoes are very soft', 'Cool before serving'],
        'All pieces should be soft enough to mash between fingers',
        'Serve on a plate with sections so they can explore each food',
      ),
      baby: v(
        'Soft Veggie & Potato Mash',
        'Baby-safe mashed potatoes with steamed vegetables',
        ['Mash roasted potatoes until smooth', 'Steam broccoli very soft and mash', 'Skip sausage if under 9mo or offer very finely minced', 'No salt, no spices'],
        ['No honey', 'Skip sausage for babies under 9mo (high sodium)', 'No added salt or spices', 'Supervise all eating'],
        'Smooth mash for 6-8mo, soft lumpy pieces for 9-12mo',
        'Roasted potato is a great first finger food — soft strips they can grip',
      ),
    },
    simplifiedSteps: [
      'Preheat oven to 425°F. Toss everything on a lined sheet pan with olive oil and garlic powder.',
      'Roast 25 minutes. Done.',
    ],
    leftoverTip: 'Chop leftovers and scramble with eggs for a quick breakfast hash.',
    keyIngredients: ['sausage', 'potatoes', 'bell peppers', 'broccoli'],
    relatedTerms: ['sheet pan', 'sausage', 'roasted vegetables', 'one pan sausage', 'sausage and potatoes', 'sheet pan dinner'],
  },

  // ─── 5. Chicken Stir-Fry ─────────────────────────────────
  {
    id: 'chicken-stir-fry',
    title: 'Chicken & Veggie Stir-Fry',
    tagline: 'Weeknight speed demon with serious flavor',
    description: 'Tender chicken strips with colorful vegetables in a savory stir-fry sauce, served over steamed rice. From cutting board to table in 20 minutes.',
    cuisineTags: ['asian'],
    proteinType: 'chicken',
    prepTime: 10,
    cookTime: 10,
    estimatedCost: 11,
    costLevel: 'medium',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'medium',
    tags: ['quick', 'high-protein', 'colorful', 'weeknight'],
    kidFriendlyScore: 7,
    dietaryCompat: ['nut-free', 'dairy-free'],
    ingredients: [
      ing('chicken breast', '1.5', 'lbs', 'protein', false, 'sliced thin'),
      ing('white rice', '1.5', 'cups', 'grain', true),
      ing('soy sauce', '3', 'tbsp', 'condiment', true),
      ing('sesame oil', '1', 'tbsp', 'condiment', true),
      ing('cornstarch', '1', 'tbsp', 'pantry_staple', true),
      ing('bell pepper', '1', 'large', 'produce', false, 'sliced'),
      ing('snap peas', '1', 'cup', 'produce'),
      ing('carrots', '2', 'medium', 'produce', false, 'julienned'),
      ing('garlic', '3', 'cloves', 'produce', false, 'minced'),
      ing('fresh ginger', '1', 'tbsp', 'produce', false, 'grated'),
      ing('vegetable oil', '2', 'tbsp', 'pantry_staple', true),
      ing('scallion', '3', 'stalks', 'produce', false, 'sliced'),
    ],
    steps: [
      'Cook rice according to package directions.',
      'Toss sliced chicken with 1 tbsp soy sauce and cornstarch. Let sit 5 minutes.',
      'Heat 1 tbsp oil in a wok or large skillet over high heat. Stir-fry chicken 4-5 minutes until cooked through. Remove and set aside.',
      'Add remaining oil. Stir-fry garlic and ginger 30 seconds.',
      'Add carrots and bell peppers; stir-fry 2 minutes. Add snap peas and cook 1 more minute.',
      'Return chicken to the wok. Add remaining soy sauce and sesame oil. Toss everything together.',
      'Serve over rice, garnished with scallions.',
    ],
    variations: {
      adult: v(
        'Chicken Stir-Fry',
        'Bold ginger-garlic stir-fry with crisp vegetables',
        ['Add chili-garlic sauce or sriracha', 'Top with toasted sesame seeds', 'Extra scallions'],
        [], null,
        'Drizzle with chili oil for an extra kick',
      ),
      kid: v(
        'Chicken & Veggie Rice Bowl',
        'Sweet, mild stir-fry with soft veggies',
        ['Use less soy sauce (1 tbsp instead of 3)', 'Skip ginger if they\'re sensitive to it', 'Cook vegetables a bit longer for softer texture', 'Add a drizzle of honey for sweetness'],
        [], null,
        'Serve the chicken on top of rice so they can mix it their way',
      ),
      toddler: v(
        'Soft Chicken & Veggie Bites',
        'Tender chicken pieces with soft steamed vegetables',
        ['Cut chicken into tiny shreds', 'Steam carrots and peppers until very soft (skip raw snap peas)', 'Minimal soy sauce (a few drops)', 'No ginger, no garlic', 'Mix with soft rice'],
        ['Ensure chicken is in small, easy-to-chew pieces', 'Avoid snap peas (tough string is a choking risk)'],
        'Very soft shredded chicken with well-steamed vegetables',
        'Let them pick up soft veggie pieces and chicken shreds with fingers',
      ),
      baby: v(
        'Chicken & Veggie Rice Mash',
        'Unseasoned chicken with soft carrots and rice',
        ['Cook a small portion of chicken without any sauce', 'Steam carrots until completely soft', 'Mash or purée chicken with rice and carrots', 'No soy sauce, no salt, no ginger'],
        ['No honey', 'No added salt or soy sauce', 'Ensure chicken is cooked through and mashed soft', 'Supervise all eating'],
        'Smooth purée for 6-8mo, soft shreds with mashed rice for 9-12mo',
        'Chicken is an excellent iron source — mash with rice for easier swallowing',
      ),
    },
    simplifiedSteps: [
      'Cook rice. Stir-fry sliced chicken in oil 5 minutes; remove.',
      'Stir-fry pre-cut frozen stir-fry vegetables 3 minutes.',
      'Return chicken, add soy sauce and sesame oil. Toss and serve over rice.',
    ],
    simplifiedSwaps: [
      { from: 'bell pepper + snap peas + carrots', to: 'frozen stir-fry vegetable mix (16 oz bag)' },
      { from: 'fresh ginger + garlic', to: 'garlic powder (1/2 tsp) + ground ginger (1/4 tsp)' },
    ],
    leftoverTip: 'Makes excellent next-day fried rice — just chop the leftovers and stir-fry with cold rice and an egg.',
    keyIngredients: ['chicken', 'rice', 'soy sauce', 'bell pepper', 'carrots', 'ginger'],
    relatedTerms: ['stir fry', 'chicken stir fry', 'stir-fry', 'chicken and vegetables', 'wok', 'asian chicken', 'chinese chicken'],
  },

  // ─── 6. Black Bean Quesadillas ────────────────────────────
  {
    id: 'black-bean-quesadillas',
    title: 'Black Bean & Cheese Quesadillas',
    tagline: '10 minutes, 5 ingredients, zero complaints',
    description: 'Crispy flour tortillas stuffed with mashed black beans, melted cheddar, and a touch of cumin. The ultimate no-brainer weeknight meal.',
    cuisineTags: ['mexican', 'comfort'],
    proteinType: 'beans',
    prepTime: 5,
    cookTime: 8,
    estimatedCost: 6,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['vegetarian', 'quick', 'pantry-friendly', 'kid-favorite', 'budget'],
    kidFriendlyScore: 10,
    dietaryCompat: ['vegetarian', 'nut-free'],
    ingredients: [
      ing('flour tortillas', '8', 'large', 'grain', true),
      ing('canned black beans', '1', 'can (15 oz)', 'pantry_staple', true, 'drained & rinsed'),
      ing('cheddar cheese', '2', 'cups', 'dairy', false, 'shredded'),
      ing('cumin', '1/2', 'tsp', 'spice', true),
      ing('butter', '2', 'tbsp', 'dairy', true),
      ing('salsa', '1/2', 'cup', 'condiment', true, 'for serving'),
      ing('sour cream', '1/4', 'cup', 'dairy', false, 'for serving'),
    ],
    steps: [
      'Roughly mash black beans in a bowl with cumin, leaving some chunks for texture.',
      'Lay out 4 tortillas. Spread bean mixture evenly on each, then top with shredded cheese.',
      'Place a second tortilla on top of each to make 4 quesadillas.',
      'Melt butter in a large skillet over medium heat. Cook each quesadilla 2-3 minutes per side until golden and cheese is melted.',
      'Cut into wedges and serve with salsa and sour cream.',
    ],
    variations: {
      adult: v(
        'Loaded Black Bean Quesadilla',
        'Crispy quesadilla with smoky beans and toppings',
        ['Add diced jalapeños or green chiles inside', 'Serve with guacamole and hot sauce', 'Add sautéed onions and peppers'],
        [], null,
        'Dip in a mix of salsa and sour cream',
      ),
      kid: v(
        'Cheesy Bean Quesadilla',
        'Extra cheesy with mild, creamy beans',
        ['Extra cheese for maximum melt', 'Skip cumin if they prefer plain', 'Cut into fun triangle shapes'],
        [], null,
        'Great for dipping in sour cream or mild salsa',
      ),
      toddler: v(
        'Mini Bean & Cheese Triangles',
        'Soft, cheesy triangles perfect for little hands',
        ['Cut into small triangles they can hold', 'Mash beans very smooth', 'Use less cheese to prevent stringy strands', 'No spices'],
        ['Ensure cheese is fully melted (no hard pieces)', 'Cool before serving — melted cheese burns easily'],
        'Soft, easy to chew — beans should be completely mashed smooth',
        'The triangle quesadilla shape is perfect for toddler grip',
      ),
      baby: v(
        'Bean & Cheese Soft Strips',
        'Soft tortilla strips with mashed beans',
        ['Mash beans completely smooth', 'Very light sprinkle of cheese melted in', 'Cut soft tortilla into graspable strips', 'No salt, no cumin'],
        ['No honey', 'No whole beans', 'Ensure tortilla is soft, not crispy', 'Supervise all eating'],
        'Soft strips for 8-12mo — beans should be completely smooth paste',
        'Soft tortilla strips are a great early finger food for pincer grasp practice',
      ),
    },
    simplifiedSteps: [
      'Spread canned refried beans on tortillas, top with cheese, fold in half.',
      'Cook in a skillet 2 min per side. Cut and serve.',
    ],
    simplifiedSwaps: [
      { from: 'canned black beans + cumin', to: 'canned refried beans (1 cup)' },
    ],
    leftoverTip: 'Reheat in a skillet (not microwave) to keep them crispy. Also great cold in a lunchbox.',
    keyIngredients: ['tortillas', 'black beans', 'cheese'],
    relatedTerms: ['quesadilla', 'quesadillas', 'bean quesadilla', 'cheese quesadilla', 'cheesy', 'tortilla', 'mexican'],
  },

  // ─── 7. Baked Mac & Cheese ────────────────────────────────
  {
    id: 'baked-mac-cheese',
    title: 'Baked Mac & Cheese',
    tagline: 'The comfort classic every family needs in rotation',
    description: 'Elbow macaroni in a rich, velvety three-cheese sauce topped with golden breadcrumbs. Pure comfort from oven to table.',
    cuisineTags: ['american', 'comfort'],
    proteinType: 'none',
    prepTime: 10,
    cookTime: 25,
    estimatedCost: 9,
    costLevel: 'low',
    servings: 6,
    difficulty: 'easy',
    energyDemand: 'medium',
    tags: ['vegetarian', 'comfort-food', 'kid-favorite', 'crowd-pleaser'],
    kidFriendlyScore: 10,
    dietaryCompat: ['vegetarian', 'nut-free'],
    ingredients: [
      ing('elbow macaroni', '1', 'lb', 'grain', true),
      ing('butter', '3', 'tbsp', 'dairy', true),
      ing('all-purpose flour', '3', 'tbsp', 'pantry_staple', true),
      ing('whole milk', '3', 'cups', 'dairy'),
      ing('sharp cheddar', '2', 'cups', 'dairy', false, 'shredded'),
      ing('mild cheddar', '1', 'cup', 'dairy', false, 'shredded'),
      ing('cream cheese', '2', 'oz', 'dairy'),
      ing('garlic powder', '1/2', 'tsp', 'spice', true),
      ing('dry mustard', '1/4', 'tsp', 'spice', true),
      ing('panko breadcrumbs', '1/2', 'cup', 'grain', true),
      ing('salt', '1/2', 'tsp', 'spice', true),
    ],
    steps: [
      'Preheat oven to 375°F (190°C). Cook macaroni one minute short of al dente; drain.',
      'In the same pot, melt butter over medium heat. Whisk in flour and cook 1 minute to form a roux.',
      'Slowly pour in milk while whisking constantly. Cook 4-5 minutes until sauce thickens.',
      'Remove from heat. Stir in cheddar cheeses, cream cheese, garlic powder, mustard, and salt until smooth.',
      'Fold in cooked macaroni. Pour into a greased 9x13 baking dish.',
      'Sprinkle panko breadcrumbs on top. Bake 20 minutes until bubbly and golden.',
    ],
    variations: {
      adult: v(
        'Three-Cheese Baked Mac',
        'Rich, golden-crusted mac with a sharp cheddar bite',
        ['Add a pinch of cayenne to the cheese sauce', 'Mix in smoked gouda for depth', 'Top with crispy bacon bits'],
        [], null,
        'Serve with a crisp green salad to balance the richness',
      ),
      kid: v(
        'Classic Mac & Cheese',
        'Creamy, golden, and exactly what they want',
        ['Use all mild cheddar for a gentler flavor', 'Skip mustard if they\'re picky about "specks"', 'Serve in a fun bowl'],
        [], null,
        'Add steamed broccoli florets mixed in for hidden veggies',
      ),
      toddler: v(
        'Soft Cheesy Macaroni',
        'Extra-soft elbow pasta in creamy cheese sauce',
        ['Cook pasta extra soft (2 minutes past al dente)', 'Use extra milk in the sauce for a thinner consistency', 'Skip breadcrumb topping (too crunchy)', 'No salt, no mustard'],
        ['Ensure pasta is very well-cooked', 'Cool to safe temperature — cheese sauce stays hot'],
        'Very soft pasta in thin, smooth cheese sauce — no crunchy topping',
        'This is usually a guaranteed hit — let them eat it their way',
      ),
      baby: v(
        'Baby Cheese Pasta',
        'Smooth cheese sauce over mashed soft pasta',
        ['Cook a small portion of pasta until very, very soft', 'Make a simple sauce: butter + milk + mild cheddar, melted smooth', 'Mash pasta with a fork', 'No salt, no mustard, no breadcrumbs'],
        ['No honey', 'No added salt', 'Check for dairy allergy/intolerance', 'Supervise all eating'],
        'Completely mashed for 6-8mo, soft small pieces for 9-12mo',
        'Let them try picking up soft elbow pieces — great for pincer grasp',
      ),
    },
    simplifiedSteps: [
      'Cook macaroni, drain. Stir in butter, milk, and shredded cheese until melted.',
      'Pour into a dish, top with breadcrumbs, bake 15 min at 375°F.',
    ],
    leftoverTip: 'Reheat with a splash of milk. Leftover mac makes great fried mac & cheese bites.',
    keyIngredients: ['macaroni', 'cheddar', 'milk', 'butter', 'flour'],
    relatedTerms: ['mac and cheese', 'mac & cheese', 'macaroni', 'macaroni and cheese', 'cheesy pasta', 'baked pasta'],
  },

  // ─── 8. Chickpea Coconut Curry ────────────────────────────
  {
    id: 'chickpea-coconut-curry',
    title: 'Chickpea Coconut Curry',
    tagline: 'Warm, fragrant, and entirely plant-powered',
    description: 'Chickpeas simmered in a creamy coconut-tomato curry sauce with warm spices. Budget-friendly, packed with protein, and deeply satisfying.',
    cuisineTags: ['indian', 'global'],
    proteinType: 'beans',
    prepTime: 5,
    cookTime: 20,
    estimatedCost: 7,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['vegan', 'vegetarian', 'budget', 'pantry-friendly', 'one-pot'],
    kidFriendlyScore: 5,
    dietaryCompat: ['vegetarian', 'vegan', 'nut-free', 'dairy-free', 'gluten-free'],
    ingredients: [
      ing('canned chickpeas', '2', 'cans (15 oz each)', 'pantry_staple', true, 'drained & rinsed'),
      ing('coconut milk', '1', 'can (13.5 oz)', 'pantry_staple', true, 'full-fat'),
      ing('canned diced tomatoes', '1', 'can (14 oz)', 'pantry_staple', true),
      ing('onion', '1', 'medium', 'produce', false, 'diced'),
      ing('garlic', '3', 'cloves', 'produce', false, 'minced'),
      ing('curry powder', '2', 'tbsp', 'spice', true),
      ing('turmeric', '1/2', 'tsp', 'spice', true),
      ing('cumin', '1', 'tsp', 'spice', true),
      ing('fresh spinach', '2', 'cups', 'produce', false, 'packed'),
      ing('olive oil', '1', 'tbsp', 'pantry_staple', true),
      ing('white rice', '1.5', 'cups', 'grain', true, 'for serving'),
    ],
    steps: [
      'Cook rice according to package directions.',
      'Heat olive oil in a large pot over medium heat. Sauté diced onion 4 minutes until soft.',
      'Add garlic, curry powder, turmeric, and cumin. Cook 1 minute until fragrant.',
      'Add diced tomatoes and coconut milk. Stir and bring to a simmer.',
      'Add chickpeas. Simmer 12-15 minutes until sauce thickens slightly.',
      'Stir in spinach and let wilt for 1 minute.',
      'Serve over steamed rice.',
    ],
    variations: {
      adult: v(
        'Chickpea Coconut Curry',
        'Warm, spice-forward curry with creamy coconut base',
        ['Add extra curry powder or garam masala', 'Top with fresh cilantro and a squeeze of lemon', 'Serve with naan bread for scooping'],
        [], null,
        'A dollop of yogurt on top cools the heat beautifully',
      ),
      kid: v(
        'Mild Coconut Chickpea Bowl',
        'Creamy, gentle curry with a sweet coconut base',
        ['Use only 1 tsp curry powder (much milder)', 'The coconut milk makes it naturally sweet — kids often love this', 'Serve chickpeas on top of rice so they can mix'],
        [], null,
        'Naan bread torn into pieces makes this more fun to eat',
      ),
      toddler: v(
        'Coconut Chickpea Mash',
        'Mashed chickpeas in a mild coconut-tomato sauce',
        ['Mash chickpeas roughly with a fork', 'Use only a pinch of turmeric (skip curry powder and cumin)', 'Extra coconut milk for a thinner sauce', 'Blend or mash spinach into the sauce', 'No salt'],
        ['Whole chickpeas can be a choking hazard — always mash', 'Cool before serving'],
        'Mashed, not whole — chunky mash with soft sauce',
        'Serve with soft rice — they can scoop with hands or a spoon',
      ),
      baby: v(
        'Coconut Chickpea Purée',
        'Smooth, protein-rich chickpea purée in mild coconut',
        ['Blend chickpeas with coconut milk and a little cooked tomato', 'No spices, no salt, no onion', 'Add steamed spinach and blend smooth', 'Thin with breast milk or formula if needed'],
        ['No honey', 'No added salt', 'No whole chickpeas', 'Supervise all eating'],
        'Smooth purée for 6-8mo, slightly chunky for 9-12mo',
        'Chickpeas are protein-and-iron-rich — excellent early food',
      ),
    },
    simplifiedSteps: [
      'Sauté diced onion. Add curry powder, canned tomatoes, coconut milk, and chickpeas.',
      'Simmer 15 minutes. Stir in spinach. Serve over rice.',
    ],
    leftoverTip: 'Gets better overnight. Freezes beautifully for up to 3 months.',
    keyIngredients: ['chickpeas', 'coconut milk', 'tomatoes', 'curry powder', 'spinach', 'rice'],
    relatedTerms: ['curry', 'chickpea curry', 'coconut curry', 'indian curry', 'chana masala', 'vegetarian curry', 'vegan curry'],
  },

  // ─── 9. Turkey Meatballs in Marinara ──────────────────────
  {
    id: 'turkey-meatball-marinara',
    title: 'Turkey Meatballs in Marinara',
    tagline: 'Lean, juicy meatballs the whole family fights over',
    description: 'Tender baked turkey meatballs in a rich marinara sauce. Serve over spaghetti, in a sub, or straight off the spoon.',
    cuisineTags: ['italian'],
    proteinType: 'turkey',
    prepTime: 15,
    cookTime: 25,
    estimatedCost: 11,
    costLevel: 'medium',
    servings: 5,
    difficulty: 'moderate',
    energyDemand: 'medium',
    tags: ['high-protein', 'lean', 'kid-friendly', 'meal-prep', 'freezer-friendly'],
    kidFriendlyScore: 9,
    dietaryCompat: ['nut-free'],
    ingredients: [
      ing('ground turkey', '1.5', 'lbs', 'protein'),
      ing('panko breadcrumbs', '1/2', 'cup', 'grain', true),
      ing('egg', '1', 'large', 'protein', true),
      ing('parmesan cheese', '1/3', 'cup', 'dairy', false, 'grated'),
      ing('garlic', '2', 'cloves', 'produce', false, 'minced'),
      ing('dried Italian seasoning', '1', 'tsp', 'spice', true),
      ing('salt', '1/2', 'tsp', 'spice', true),
      ing('marinara sauce', '1', 'jar (24 oz)', 'pantry_staple', true),
      ing('spaghetti', '1', 'lb', 'grain', true),
      ing('fresh basil', '4-5', 'leaves', 'produce', false, 'for garnish'),
    ],
    steps: [
      'Preheat oven to 400°F (200°C). Line a baking sheet with parchment.',
      'In a large bowl, combine turkey, breadcrumbs, egg, parmesan, garlic, Italian seasoning, and salt. Mix gently — don\'t overwork.',
      'Roll into 20 meatballs (about 1.5 inches each). Place on prepared sheet.',
      'Bake 18-20 minutes until cooked through (internal temp 165°F).',
      'While meatballs bake, cook spaghetti and heat marinara sauce in a pot.',
      'Add baked meatballs to the marinara sauce and simmer 5 minutes to meld flavors.',
      'Serve meatballs and sauce over spaghetti, garnished with fresh basil.',
    ],
    variations: {
      adult: v(
        'Turkey Meatballs Marinara',
        'Herb-packed meatballs in rich tomato sauce over spaghetti',
        ['Add red pepper flakes to the marinara', 'Extra parmesan on top', 'Serve with garlic bread'],
        [], null,
        'These also make incredible meatball subs',
      ),
      kid: v(
        'Spaghetti & Meatballs',
        'The classic kid dinner — impossible to refuse',
        ['Keep sauce mild (no pepper flakes)', 'Cut meatballs in half for easier eating', 'Fun to twirl spaghetti with a fork'],
        [], null,
        'Let them count their meatballs — makes eating a game',
      ),
      toddler: v(
        'Mini Meatball Pasta',
        'Tiny soft meatballs with short pasta in smooth sauce',
        ['Make meatballs smaller (1 inch)', 'Use short pasta like penne or rotini instead of spaghetti', 'Blend marinara smooth', 'Cook pasta extra soft', 'No salt in the meatball mix'],
        ['Cut each meatball into quarters', 'Avoid long spaghetti (choking risk)'],
        'Soft, small meatball pieces with smooth sauce and well-cooked short pasta',
        'Toddlers love picking up small meatball pieces — great protein intake',
      ),
      baby: v(
        'Turkey Meatball Mash',
        'Soft, plain turkey mash with smooth tomato sauce',
        ['Make 2-3 meatballs without salt, seasoning, or parmesan', 'Bake until cooked through, then mash finely', 'Mix with a spoonful of smooth marinara (low-sodium)', 'Serve with mashed soft pasta', 'No egg in baby portion if under 12mo and not yet introduced'],
        ['No honey', 'No added salt', 'Check egg allergy status', 'Ensure turkey is fully cooked and mashed', 'Supervise all eating'],
        'Finely mashed for 6-8mo, soft small pieces for 9-12mo',
        'Turkey is lean and mild — an excellent early protein',
      ),
    },
    simplifiedSteps: [
      'Mix turkey with breadcrumbs, egg, and Italian seasoning. Roll into balls.',
      'Bake at 400°F for 20 min. Cook pasta.',
      'Toss meatballs in jarred marinara. Serve over pasta.',
    ],
    leftoverTip: 'Meatballs freeze beautifully — make a double batch. Reheat from frozen in sauce.',
    keyIngredients: ['ground turkey', 'marinara sauce', 'spaghetti', 'egg', 'breadcrumbs', 'parmesan'],
    relatedTerms: ['meatballs', 'turkey meatballs', 'spaghetti and meatballs', 'meatball', 'marinara', 'italian meatballs', 'pasta and meatballs'],
  },

  // ─── 10. Egg Fried Rice ───────────────────────────────────
  {
    id: 'egg-fried-rice',
    title: 'Egg Fried Rice',
    tagline: 'The ultimate 10-minute fridge-cleanout meal',
    description: 'Quick-fried rice with scrambled eggs, crisp vegetables, and savory soy sauce. Uses leftover rice and whatever veggies you have.',
    cuisineTags: ['asian'],
    proteinType: 'eggs',
    prepTime: 5,
    cookTime: 8,
    estimatedCost: 5,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['quick', 'budget', 'pantry-friendly', 'leftover-friendly', 'one-pan'],
    kidFriendlyScore: 8,
    dietaryCompat: ['vegetarian', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('cooked rice', '4', 'cups', 'grain', true, 'day-old is best'),
      ing('eggs', '3', 'large', 'protein', true),
      ing('frozen peas and carrots', '1', 'cup', 'produce', true),
      ing('soy sauce', '2', 'tbsp', 'condiment', true),
      ing('sesame oil', '1', 'tsp', 'condiment', true),
      ing('garlic', '2', 'cloves', 'produce', false, 'minced'),
      ing('vegetable oil', '2', 'tbsp', 'pantry_staple', true),
      ing('scallion', '3', 'stalks', 'produce', false, 'sliced'),
    ],
    steps: [
      'Heat 1 tbsp oil in a large skillet or wok over high heat.',
      'Scramble eggs quickly, break into small pieces. Remove and set aside.',
      'Add remaining oil. Sauté garlic 20 seconds, then add frozen peas and carrots. Cook 2 minutes.',
      'Add rice and press flat against the pan. Let it sear 1-2 minutes without stirring for crispy bits.',
      'Toss rice, add soy sauce and sesame oil, stir to coat evenly.',
      'Return scrambled eggs to the pan, toss to combine. Top with scallions.',
    ],
    variations: {
      adult: v(
        'Classic Egg Fried Rice',
        'Savory wok-fried rice with crispy edges',
        ['Add white pepper and extra soy sauce', 'Top with a fried egg for richness', 'Drizzle with chili crisp'],
        [], null,
        'Tastes best eaten straight from the wok',
      ),
      kid: v(
        'Egg & Veggie Rice',
        'Mild fried rice with scrambled egg mixed in',
        ['Use less soy sauce for lower sodium', 'Keep the egg scramble soft', 'Add corn for sweetness they love'],
        [], null,
        'Sprinkle a little ketchup on the side for dipping (trust the process)',
      ),
      toddler: v(
        'Soft Egg Rice Bowl',
        'Well-cooked rice with soft scrambled egg and peas',
        ['Scramble eggs very soft', 'Ensure peas are fully cooked and slightly mashed', 'Minimal soy sauce (a few drops)', 'No garlic'],
        ['Peas can be a choking hazard — press each one to pop before serving', 'Cool before serving'],
        'Soft, sticky rice with soft egg and mashed peas',
        'Sticky rice is easy for toddlers to grab in clumps',
      ),
      baby: v(
        'Egg & Rice Mash',
        'Soft scrambled egg mashed into rice with vegetables',
        ['Scramble egg until well-cooked, mash finely', 'Mix with very soft rice', 'Mash peas completely', 'No soy sauce, no salt, no garlic'],
        ['No honey', 'No added salt or soy sauce', 'Check egg allergy status before serving', 'Mash all peas (choking hazard when whole)', 'Supervise all eating'],
        'Mashed smooth for 6-8mo, soft lumpy for 9-12mo',
        'Egg yolk is fine from 6mo — introduce carefully and watch for reactions',
      ),
    },
    simplifiedSteps: [
      'Scramble eggs, pushto the side. Add leftover rice and frozen veggies.',
      'Add soy sauce, toss everything together. Done.',
    ],
    leftoverTip: 'Best eaten fresh. If storing, add a splash of soy sauce when reheating.',
    keyIngredients: ['rice', 'eggs', 'soy sauce', 'peas', 'carrots'],
    relatedTerms: ['fried rice', 'egg fried rice', 'leftover rice', 'rice bowl', 'chinese rice', 'quick rice'],
  },

  // ─── 11. Lentil Soup ─────────────────────────────────────
  {
    id: 'lentil-soup',
    title: 'Hearty Red Lentil Soup',
    tagline: 'One pot, big nutrition, tiny price tag',
    description: 'Red lentils simmered with carrots, onions, and warm spices until creamy and thick. Protein-rich, fiber-packed, and costs almost nothing to make.',
    cuisineTags: ['global', 'mediterranean'],
    proteinType: 'lentils',
    prepTime: 5,
    cookTime: 25,
    estimatedCost: 5,
    costLevel: 'low',
    servings: 6,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['vegan', 'vegetarian', 'budget', 'pantry-friendly', 'one-pot', 'high-fiber', 'meal-prep'],
    kidFriendlyScore: 6,
    dietaryCompat: ['vegetarian', 'vegan', 'nut-free', 'dairy-free', 'gluten-free'],
    ingredients: [
      ing('red lentils', '1.5', 'cups', 'pantry_staple', true, 'rinsed'),
      ing('carrots', '2', 'medium', 'produce', false, 'diced'),
      ing('onion', '1', 'medium', 'produce', false, 'diced'),
      ing('garlic', '3', 'cloves', 'produce', false, 'minced'),
      ing('vegetable broth', '6', 'cups', 'pantry_staple', true),
      ing('canned diced tomatoes', '1', 'can (14 oz)', 'pantry_staple', true),
      ing('cumin', '1', 'tsp', 'spice', true),
      ing('turmeric', '1/2', 'tsp', 'spice', true),
      ing('smoked paprika', '1/2', 'tsp', 'spice', true),
      ing('olive oil', '2', 'tbsp', 'pantry_staple', true),
      ing('lemon juice', '1', 'tbsp', 'condiment', true),
      ing('salt', '', 'to taste', 'spice', true),
    ],
    steps: [
      'Heat olive oil in a large pot over medium heat. Sauté onion and carrots 4 minutes until softened.',
      'Add garlic, cumin, turmeric, and paprika. Cook 1 minute until fragrant.',
      'Add rinsed lentils, diced tomatoes, and vegetable broth. Stir to combine.',
      'Bring to a boil, then reduce heat and simmer 20-22 minutes until lentils are completely soft and falling apart.',
      'Stir in lemon juice. Season with salt. The soup will naturally thicken as lentils break down.',
      'For creamier soup, blend half with an immersion blender (optional).',
    ],
    variations: {
      adult: v(
        'Hearty Red Lentil Soup',
        'Rich, warming soup with cumin and a bright lemon finish',
        ['Top with a swirl of olive oil and smoked paprika', 'Serve with crusty bread for dipping', 'Add harissa paste for smoky heat'],
        [], null,
        'This soup gets better on day two — make extra',
      ),
      kid: v(
        'Creamy Lentil Soup',
        'Smooth, mild soup that\'s naturally sweet from the carrots',
        ['Blend smooth — kids prefer no chunks', 'The carrots add natural sweetness', 'Use less cumin (1/4 tsp)', 'Serve with a grilled cheese for dunking'],
        [], null,
        'A grilled cheese dunked in this soup is absolute magic',
      ),
      toddler: v(
        'Smooth Lentil Veggie Soup',
        'Blended smooth, packed with hidden vegetables',
        ['Blend completely smooth', 'Use less spice (just a pinch of turmeric)', 'No salt', 'Thin with extra broth if needed'],
        ['Cool before serving — soup stays hot a long time', 'Test temperature carefully'],
        'Completely smooth, pourable consistency',
        'Serve in a sippy cup or open cup for self-feeding practice',
      ),
      baby: v(
        'Lentil Veggie Purée',
        'Iron-rich lentil purée with carrots — a perfect first food',
        ['Cook lentils and carrots with plain water (no broth)', 'Blend completely smooth', 'No spices, no salt, no onion for under 9mo', 'Thin with breast milk or formula'],
        ['No honey', 'No added salt', 'No stock cubes (too much sodium)', 'Supervise all eating'],
        'Completely smooth thin purée for 6-8mo, thicker purée for 9-12mo',
        'Red lentils are iron + protein powerhouse — excellent for 6mo+ babies',
      ),
    },
    simplifiedSteps: [
      'Put everything in a pot: lentils, broth, canned tomatoes, diced carrots, spices.',
      'Bring to boil, simmer 22 minutes. Squeeze in lemon. Done.',
    ],
    leftoverTip: 'Freezes for up to 3 months. Thickens as it cools — add water when reheating.',
    keyIngredients: ['lentils', 'carrots', 'tomatoes', 'vegetable broth', 'cumin'],
    relatedTerms: ['lentil soup', 'red lentil', 'lentil', 'dal', 'dhal', 'soup', 'vegetable soup'],
  },

  // ─── 12. Honey Garlic Chicken ─────────────────────────────
  {
    id: 'honey-garlic-chicken',
    title: 'Honey Garlic Chicken Thighs',
    tagline: 'Sticky, sweet, garlicky — pure weeknight gold',
    description: 'Juicy chicken thighs glazed in a sweet and savory honey-garlic sauce, seared to golden perfection. Served with rice and steamed green beans.',
    cuisineTags: ['asian', 'american', 'comfort'],
    proteinType: 'chicken',
    prepTime: 5,
    cookTime: 20,
    estimatedCost: 10,
    costLevel: 'medium',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'medium',
    tags: ['quick', 'kid-friendly', 'high-protein', 'gluten-free'],
    kidFriendlyScore: 9,
    dietaryCompat: ['nut-free', 'dairy-free', 'gluten-free'],
    ingredients: [
      ing('bone-in chicken thighs', '8', 'pieces', 'protein'),
      ing('honey', '3', 'tbsp', 'pantry_staple', true),
      ing('soy sauce', '3', 'tbsp', 'condiment', true),
      ing('garlic', '5', 'cloves', 'produce', false, 'minced'),
      ing('butter', '1', 'tbsp', 'dairy', true),
      ing('olive oil', '1', 'tbsp', 'pantry_staple', true),
      ing('white rice', '1.5', 'cups', 'grain', true),
      ing('green beans', '12', 'oz', 'produce', false, 'trimmed'),
      ing('black pepper', '', 'to taste', 'spice', true),
    ],
    steps: [
      'Cook rice according to package directions.',
      'Season chicken thighs with pepper. Heat olive oil in a large oven-safe skillet over medium-high heat.',
      'Sear chicken skin-side down for 5-6 minutes until golden. Flip and cook 3 more minutes.',
      'In a small bowl, mix honey, soy sauce, and minced garlic.',
      'Pour sauce over chicken. Add butter to the pan. Reduce heat to medium and simmer 10 minutes, spooning sauce over chicken frequently, until chicken is cooked through.',
      'Meanwhile, steam green beans until tender-crisp, about 4 minutes.',
      'Serve chicken over rice with green beans, spooning pan sauce over everything.',
    ],
    variations: {
      adult: v(
        'Sticky Honey Garlic Chicken',
        'Rich, caramelized thighs with a savory-sweet glaze',
        ['Add red pepper flakes to the sauce for heat', 'Squeeze of lime at the end', 'Garnish with sesame seeds and scallions'],
        [], null,
        'Save the pan sauce — it\'s liquid gold over the rice',
      ),
      kid: v(
        'Sweet Honey Chicken',
        'Sweet glazed chicken that kids demolish',
        ['The sweet honey glaze is naturally kid-approved', 'Cut chicken off the bone for easier eating', 'Serve green beans on the side, not mixed in'],
        ['Ensure no small bones in their portion'], null,
        'Dipping the chicken in extra sauce makes it interactive',
      ),
      toddler: v(
        'Soft Honey Chicken Bites',
        'Tender, boneless chicken pieces in mild sweet glaze',
        ['Remove all bones and skin', 'Shred or cut into small tender pieces', 'Use a very thin glaze (dilute sauce with water)', 'Steam green beans until very soft and cut into small pieces'],
        ['Remove all bones and cartilage', 'Cut into small, easy-to-chew pieces', 'Cool the sticky glaze — it stays hot'],
        'Soft shredded chicken with a mild sweet glaze',
        'Sticky chicken is fun to grab — expect messy hands',
      ),
      baby: v(
        'Soft Chicken & Green Bean Mash',
        'Plain, tender chicken mashed with vegetables',
        ['Cook a portion of chicken without honey or soy sauce', 'Shred or mash chicken very finely', 'Steam green beans until completely soft and mash', 'Mix with soft rice', 'No honey (critical for under 1 year), no salt'],
        ['CRITICAL: No honey for babies under 12 months (botulism risk)', 'No added salt or soy sauce', 'Ensure chicken is boneless and mashed', 'Supervise all eating'],
        'Finely mashed for 6-8mo, soft shreds for 9-12mo',
        'Chicken thigh is more tender and flavorful than breast for babies',
      ),
    },
    simplifiedSteps: [
      'Cook rice. Sear chicken thighs 5 min per side in a skillet.',
      'Pour honey + soy sauce + garlic over chicken. Simmer 10 min.',
      'Steam green beans. Plate and serve.',
    ],
    leftoverTip: 'Shred leftover chicken and toss with rice and veggies for a stir-fry bowl.',
    keyIngredients: ['chicken', 'honey', 'soy sauce', 'garlic', 'rice', 'green beans'],
    relatedTerms: ['honey garlic chicken', 'honey chicken', 'garlic chicken', 'sticky chicken', 'chicken thighs', 'glazed chicken'],
  },
  ...MEALS_NEPALI,
  ...MEALS_EXTENDED,
]
