// ============================================================
// Smart Meal Engine — Nepali Meal Database
// ============================================================

import type { MealCandidate } from './types'
import { ing, v } from './meals'

export const MEALS_NEPALI: MealCandidate[] = [
  // ─── 1. Dal Bhat (Lentil Soup with Rice) ──────────────────
  {
    id: 'nepali-dal-bhat',
    title: 'Dal Bhat',
    tagline: 'Nepal\'s beloved everyday comfort — lentil soup with fluffy rice',
    description: 'The national dish of Nepal. Perfectly spiced yellow lentil soup (dal) served over steamed basmati rice with a side of sautéed greens and pickle (achar). Nutritious, warming, and endlessly satisfying.',
    cuisineTags: ['nepali'],
    proteinType: 'lentils',
    prepTime: 10,
    cookTime: 30,
    estimatedCost: 6,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['staple', 'vegetarian', 'high-protein', 'gluten-free', 'budget-friendly', 'one-pot'],
    kidFriendlyScore: 8,
    dietaryCompat: ['vegetarian', 'vegan', 'gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('yellow lentils (masoor dal)', '1', 'cup', 'protein'),
      ing('basmati rice', '2', 'cups', 'grain', true),
      ing('turmeric powder', '1/2', 'tsp', 'spice', true),
      ing('cumin seeds', '1', 'tsp', 'spice', true),
      ing('garlic', '4', 'cloves', 'produce'),
      ing('ginger', '1', 'inch piece', 'produce'),
      ing('onion', '1', 'medium', 'produce'),
      ing('tomato', '1', 'medium', 'produce'),
      ing('green chili', '1', '', 'produce'),
      ing('ghee or oil', '2', 'tbsp', 'pantry_staple', true),
      ing('salt', '', 'to taste', 'spice', true),
      ing('cilantro', '2', 'tbsp', 'produce', false, 'for garnish'),
      ing('spinach or mustard greens', '2', 'cups', 'produce', false, 'for tarkari side'),
    ],
    steps: [
      'Wash lentils until water runs clear. Add to a pot with 3 cups water, turmeric, and a pinch of salt. Boil, then simmer 20 minutes until soft and creamy.',
      'Cook basmati rice separately — rinse, soak 15 min, cook with 1:1.5 water ratio.',
      'For the tadka (tempering): heat ghee in a small pan, add cumin seeds until they sizzle.',
      'Add minced garlic, ginger, and sliced onion. Sauté until golden, about 4 minutes.',
      'Add diced tomato and green chili. Cook 3 minutes until tomato softens.',
      'Pour the tadka into the cooked dal. Stir and simmer 5 more minutes.',
      'Sauté greens with a little oil, garlic, and salt for the tarkari side.',
      'Serve dal over rice with greens on the side. Garnish with fresh cilantro.',
    ],
    variations: {
      adult: v(
        'Dal Bhat Tarkari',
        'Full plate with spiced dal, rice, greens, and pickle',
        ['Serve with tomato achar (pickle) on the side', 'Add a squeeze of lemon', 'Extra green chili for heat'],
        [], null,
        'Eat with your right hand for the authentic experience — mix dal into rice',
      ),
      kid: v(
        'Mild Dal Rice Bowl',
        'Creamy mild lentils mixed into rice',
        ['Skip green chili entirely', 'Mix dal directly into rice for easier eating', 'Add a tiny drizzle of ghee on top'],
        [], null,
        'Shape the rice into a small mound — kids love scooping the dal over it',
      ),
      toddler: v(
        'Soft Dal & Rice Mash',
        'Well-cooked lentils mashed with soft rice',
        ['Cook lentils extra soft', 'Mash rice and dal together', 'Skip chili and reduce spices', 'Add a little ghee for calories'],
        ['Ensure no whole spice seeds remain', 'Test temperature before serving'],
        'Smooth, porridge-like consistency — dal naturally softens beautifully',
        'Dal bhat is a perfect first food introduction to Nepali cuisine',
      ),
      baby: v(
        'Lentil Rice Purée',
        'Smooth blended dal with soft rice — nutrient-rich first food',
        ['Cook lentils until very soft', 'Blend dal and rice together until smooth', 'No salt, no chili, minimal spice', 'Add breast milk or formula for consistency'],
        ['No salt for babies under 12 months', 'No honey', 'Supervise all eating'],
        'Completely smooth purée for 6-8mo, slightly textured for 9-12mo',
        'Dal is an excellent iron-rich first food for babies',
      ),
    },
    leftoverTip: 'Dal thickens overnight — add water when reheating. Stores 3-4 days refrigerated.',
    keyIngredients: ['lentils', 'rice', 'turmeric', 'cumin', 'garlic', 'ginger'],
    relatedTerms: ['dal bhat', 'daal bhaat', 'nepali lentils', 'lentil soup', 'nepali rice', 'tarkari'],
  },

  // ─── 2. Chicken Momo ──────────────────────────────────────
  {
    id: 'nepali-chicken-momo',
    title: 'Chicken Momo',
    tagline: 'Nepal\'s iconic steamed dumplings with spicy tomato chutney',
    description: 'Juicy chicken filling wrapped in delicate hand-rolled dough, steamed to perfection. Served with fiery tomato-sesame achar. The undisputed king of Nepali street food.',
    cuisineTags: ['nepali'],
    proteinType: 'chicken',
    prepTime: 40,
    cookTime: 15,
    estimatedCost: 12,
    costLevel: 'medium',
    servings: 4,
    difficulty: 'moderate',
    energyDemand: 'high',
    tags: ['steamed', 'dumpling', 'street-food', 'high-protein', 'crowd-pleaser'],
    kidFriendlyScore: 9,
    dietaryCompat: ['nut-free', 'dairy-free'],
    ingredients: [
      ing('ground chicken', '1', 'lb', 'protein'),
      ing('onion', '1', 'large', 'produce', false, 'finely minced'),
      ing('cilantro', '1/4', 'cup', 'produce', false, 'finely chopped'),
      ing('garlic', '4', 'cloves', 'produce', false, 'minced'),
      ing('ginger', '1', 'inch piece', 'produce', false, 'grated'),
      ing('soy sauce', '1', 'tbsp', 'condiment', true),
      ing('cumin powder', '1/2', 'tsp', 'spice', true),
      ing('black pepper', '1/2', 'tsp', 'spice', true),
      ing('sesame oil', '1', 'tsp', 'condiment'),
      ing('all-purpose flour', '2', 'cups', 'grain', true),
      ing('water', '3/4', 'cup', 'other', true, 'for dough'),
      ing('oil', '1', 'tsp', 'pantry_staple', true, 'for dough'),
      ing('tomatoes', '3', 'medium', 'produce', false, 'for achar'),
      ing('sesame seeds', '2', 'tbsp', 'spice', false, 'for achar'),
      ing('dried red chilies', '3', '', 'spice', true, 'for achar'),
      ing('timur (Sichuan pepper)', '1/2', 'tsp', 'spice', false, 'for achar'),
    ],
    steps: [
      'Make the dough: mix flour, water, and a tsp of oil. Knead 8-10 minutes until smooth. Cover and rest 30 minutes.',
      'Make the filling: combine ground chicken, minced onion, cilantro, garlic, ginger, soy sauce, cumin, pepper, and sesame oil. Mix well.',
      'Make the achar: dry-roast tomatoes, chilies, sesame seeds, and timur. Blend into a chunky chutney with salt.',
      'Roll dough into small thin circles (about 3 inches). Place a spoonful of filling in the center.',
      'Pleat and seal the edges by pinching the dough together at the top, creating the classic momo shape.',
      'Oil the steamer basket. Arrange momos without touching. Steam over boiling water for 12-15 minutes.',
      'Serve hot with tomato-sesame achar on the side.',
    ],
    variations: {
      adult: v(
        'Classic Chicken Momo',
        'Spicy, juicy dumplings with fiery achar',
        ['Extra timur in the achar for numbing heat', 'Serve with jhol achar (soupy chutney) as well', 'Pan-fry after steaming for crispy kothey momo'],
        [], null,
        'Dip generously in achar — the spicier, the better',
      ),
      kid: v(
        'Mini Chicken Momos',
        'Mild, juicy dumplings with gentle dipping sauce',
        ['Skip chili in the filling', 'Make smaller momos for little hands', 'Serve with mild ketchup or soy dipping sauce instead of spicy achar'],
        [], null,
        'Kids love the dumpling shape — let them try dipping themselves',
      ),
      toddler: v(
        'Soft Chicken Momo Bites',
        'Tender steamed dumplings cut into pieces',
        ['Make very small momos with extra-thin wrapper', 'Ensure filling is very finely ground', 'Cut each momo in half before serving', 'Skip all spicy elements'],
        ['Cut into small pieces to prevent choking', 'Check internal temperature reaches 165°F', 'Let cool before serving'],
        'Soft, well-steamed wrapper with finely ground filling',
        'The soft texture of steamed momos is great for toddlers learning to chew',
      ),
      baby: v(
        'Steamed Chicken Mince',
        'Plain steamed seasoned chicken without wrapper',
        ['Use just the filling mixture without wrapper', 'Steam the chicken filling in small portions', 'Mash or shred very finely', 'Skip soy sauce and use minimal seasoning', 'No achar'],
        ['No soy sauce for very young babies', 'Ensure chicken is cooked through', 'Mash to appropriate texture', 'Supervise all eating'],
        'Finely mashed for 6-8mo, small soft shreds for 9-12mo',
        'The ginger and garlic add gentle flavor babies often enjoy',
      ),
    },
    simplifiedSteps: [
      'Use store-bought dumpling wrappers. Mix filling ingredients together.',
      'Fill, fold, and steam for 12-15 minutes.',
      'Serve with store-bought chili sauce.',
    ],
    simplifiedSwaps: [
      { from: 'hand-rolled dough', to: 'store-bought dumpling wrappers' },
      { from: 'homemade achar', to: 'store-bought sweet chili sauce' },
    ],
    leftoverTip: 'Freeze uncooked momos on a tray, then bag them. Steam from frozen adding 3-4 extra minutes.',
    keyIngredients: ['chicken', 'flour', 'onion', 'garlic', 'ginger', 'tomato', 'sesame'],
    relatedTerms: ['momo', 'momos', 'nepali dumpling', 'chicken dumpling', 'steamed dumpling', 'nepal momo', 'dim sum'],
  },

  // ─── 3. Aloo Tama (Potato & Bamboo Shoot Curry) ──────────
  {
    id: 'nepali-aloo-tama',
    title: 'Aloo Tama',
    tagline: 'Hearty potato and bamboo shoot curry with black-eyed peas',
    description: 'A traditional Newari curry featuring tender potatoes, tangy fermented bamboo shoots, and black-eyed peas in a warming turmeric-cumin broth. Uniquely Nepali and deeply satisfying.',
    cuisineTags: ['nepali'],
    proteinType: 'beans',
    prepTime: 15,
    cookTime: 35,
    estimatedCost: 7,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['curry', 'vegetarian', 'vegan', 'traditional', 'budget-friendly', 'gluten-free'],
    kidFriendlyScore: 6,
    dietaryCompat: ['vegetarian', 'vegan', 'gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('potatoes', '3', 'medium', 'produce'),
      ing('fermented bamboo shoots (tama)', '1', 'cup', 'produce', false, 'soaked and rinsed'),
      ing('black-eyed peas', '1/2', 'cup', 'protein', false, 'soaked overnight or canned'),
      ing('turmeric powder', '1/2', 'tsp', 'spice', true),
      ing('cumin seeds', '1', 'tsp', 'spice', true),
      ing('fenugreek seeds', '1/4', 'tsp', 'spice'),
      ing('onion', '1', 'medium', 'produce'),
      ing('tomato', '1', 'medium', 'produce'),
      ing('garlic', '3', 'cloves', 'produce'),
      ing('ginger', '1', 'inch piece', 'produce'),
      ing('green chili', '1', '', 'produce'),
      ing('oil', '2', 'tbsp', 'pantry_staple', true),
      ing('salt', '', 'to taste', 'spice', true),
      ing('cilantro', '2', 'tbsp', 'produce', false, 'for garnish'),
    ],
    steps: [
      'If using dried bamboo shoots, soak in water overnight and rinse well to reduce sourness. If canned, rinse thoroughly.',
      'If using dried black-eyed peas, soak overnight and boil until tender (about 25 min). Drain.',
      'Peel and cube potatoes into 1-inch pieces.',
      'Heat oil in a pot. Add fenugreek and cumin seeds — let them sizzle for 10 seconds.',
      'Add sliced onion, garlic, and ginger. Sauté 3 minutes until fragrant.',
      'Add turmeric, diced tomato, and green chili. Cook 2 minutes.',
      'Add potatoes, bamboo shoots, and black-eyed peas. Stir to coat with spices.',
      'Add 2 cups water. Bring to a boil, then simmer covered for 25 minutes until potatoes are tender.',
      'Adjust salt and garnish with cilantro. Serve with steamed rice.',
    ],
    variations: {
      adult: v(
        'Aloo Tama Bodi',
        'Full-bodied curry with tangy bamboo shoots',
        ['Extra green chili for heat', 'Add a squeeze of lime before serving', 'Pair with steamed rice and pickle'],
        [], null,
        'The tangy bamboo shoot flavor is an acquired taste — embrace it!',
      ),
      kid: v(
        'Mild Potato & Bean Curry',
        'Potato-forward curry with less bamboo shoot',
        ['Reduce bamboo shoots or skip if too tangy for kids', 'Skip green chili', 'Extra potato for a milder, creamier curry'],
        [], null,
        'Serve over rice — kids love the soft potato chunks',
      ),
      toddler: v(
        'Soft Potato & Bean Mash',
        'Mashed potatoes with tender beans in mild broth',
        ['Mash potatoes and beans together', 'Skip bamboo shoots entirely', 'Use minimal spice — just turmeric', 'Extra soft cook everything'],
        ['Mash to prevent choking on potato chunks', 'Check temperature'],
        'Soft mashed consistency with no large chunks',
        'Turmeric is great for toddlers — anti-inflammatory and mild in flavor',
      ),
      baby: v(
        'Potato & Lentil Purée',
        'Smooth potato purée with protein-rich beans',
        ['Use just potatoes and well-cooked black-eyed peas', 'Blend until smooth', 'A pinch of turmeric only', 'No salt, no chili'],
        ['No salt for babies', 'Ensure beans are very soft', 'Blend thoroughly', 'Supervise all eating'],
        'Smooth purée for 6-8mo, soft mashed for 9-12mo',
        'Potato makes an excellent base for introducing legumes',
      ),
    },
    leftoverTip: 'Tastes even better the next day as flavors develop. Stores 3-4 days refrigerated.',
    keyIngredients: ['potato', 'bamboo shoots', 'black-eyed peas', 'turmeric', 'cumin'],
    relatedTerms: ['aloo tama', 'alu tama', 'bamboo shoot curry', 'nepali curry', 'newari food', 'tama curry'],
  },

  // ─── 4. Gundruk Ko Jhol (Fermented Greens Soup) ──────────
  {
    id: 'nepali-gundruk-jhol',
    title: 'Gundruk Ko Jhol',
    tagline: 'Tangy fermented greens soup — a Nepali superfood classic',
    description: 'A light, tangy, and deeply savory soup made from gundruk (fermented leafy greens). Rich in probiotics and iron, this traditional dish is comfort food at its most nourishing.',
    cuisineTags: ['nepali'],
    proteinType: 'none',
    prepTime: 10,
    cookTime: 20,
    estimatedCost: 4,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['soup', 'vegetarian', 'vegan', 'probiotic', 'iron-rich', 'budget-friendly', 'gluten-free'],
    kidFriendlyScore: 4,
    dietaryCompat: ['vegetarian', 'vegan', 'gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('gundruk (dried fermented greens)', '1', 'cup', 'produce'),
      ing('potato', '1', 'medium', 'produce', false, 'cubed'),
      ing('tomato', '1', 'medium', 'produce'),
      ing('onion', '1', 'small', 'produce'),
      ing('garlic', '3', 'cloves', 'produce'),
      ing('green chili', '1', '', 'produce'),
      ing('turmeric', '1/4', 'tsp', 'spice', true),
      ing('cumin seeds', '1/2', 'tsp', 'spice', true),
      ing('fenugreek seeds', '1/4', 'tsp', 'spice'),
      ing('mustard oil', '1', 'tbsp', 'pantry_staple'),
      ing('salt', '', 'to taste', 'spice', true),
      ing('water', '4', 'cups', 'other', true),
    ],
    steps: [
      'Soak gundruk in warm water for 15 minutes. Rinse well and squeeze out excess water. Chop roughly.',
      'Heat mustard oil in a pot until it just begins to smoke, then reduce heat.',
      'Add fenugreek and cumin seeds. Let sizzle for 10 seconds.',
      'Add sliced onion and garlic. Sauté until light golden.',
      'Add diced tomato, green chili, and turmeric. Cook 2 minutes.',
      'Add gundruk and cubed potato. Stir to combine.',
      'Add 4 cups water. Bring to a boil, then simmer for 15-20 minutes until potato is tender.',
      'Adjust salt. Serve hot as a side soup with dal bhat.',
    ],
    variations: {
      adult: v(
        'Gundruk Ko Jhol',
        'Tangy, savory fermented greens soup',
        ['Extra chili for spice', 'A squeeze of lime juice brightens it up', 'Serve alongside rice and dal'],
        [], null,
        'Sip the broth — it\'s deeply savory and probiotic-rich',
      ),
      kid: v(
        'Mild Veggie Soup',
        'Light potato soup with greens',
        ['Use less gundruk for milder flavor', 'Skip green chili', 'Extra potato for a heartier soup'],
        [], null,
        'If the tangy flavor is too strong, reduce gundruk and add more potato',
      ),
      toddler: v(
        'Soft Potato Greens Soup',
        'Mild, soft soup with potato and gentle greens',
        ['Very small amount of gundruk or skip', 'Mash potato pieces', 'No chili, minimal spice'],
        ['Mash or blend to safe texture', 'Test temperature'],
        'Soft, soupy consistency with mashed potatoes',
        'The broth is hydrating and nutritious for toddlers',
      ),
      baby: v(
        'Potato Veggie Broth',
        'Mild potato broth — skip fermented greens for babies',
        ['Use just potato, mild spice, and broth', 'Skip gundruk entirely for babies', 'Blend smooth', 'No salt'],
        ['No fermented foods for very young babies', 'No salt', 'Supervise all eating'],
        'Smooth blended soup for 6-8mo, slightly chunky for 9-12mo',
        'A warm, gentle introduction to savory flavors',
      ),
    },
    leftoverTip: 'Stores 2-3 days. The tang mellows slightly overnight.',
    keyIngredients: ['gundruk', 'potato', 'tomato', 'mustard oil', 'cumin'],
    relatedTerms: ['gundruk', 'gundrook', 'fermented greens', 'nepali soup', 'jhol', 'probiotic soup'],
  },

  // ─── 5. Sel Roti (Nepali Rice Ring Bread) ─────────────────
  {
    id: 'nepali-sel-roti',
    title: 'Sel Roti',
    tagline: 'Sweet crispy rice ring bread — Nepal\'s festive treat',
    description: 'A traditional Nepali ring-shaped bread made from rice flour batter, lightly sweetened and deep-fried to golden perfection. Essential during Dashain and Tihar festivals.',
    cuisineTags: ['nepali'],
    proteinType: 'none',
    prepTime: 20,
    cookTime: 20,
    estimatedCost: 5,
    costLevel: 'low',
    servings: 6,
    difficulty: 'moderate',
    energyDemand: 'medium',
    tags: ['bread', 'festive', 'snack', 'sweet', 'traditional', 'gluten-free', 'vegetarian'],
    kidFriendlyScore: 9,
    dietaryCompat: ['vegetarian', 'gluten-free', 'nut-free'],
    ingredients: [
      ing('rice flour', '2', 'cups', 'grain'),
      ing('sugar', '1/2', 'cup', 'pantry_staple', true),
      ing('banana', '1', 'ripe', 'produce', false, 'mashed'),
      ing('ghee', '2', 'tbsp', 'dairy', false, 'melted'),
      ing('cardamom powder', '1/2', 'tsp', 'spice'),
      ing('clove powder', '1/4', 'tsp', 'spice'),
      ing('warm water or milk', '1', 'cup', 'other', true, 'approximately'),
      ing('oil', '3', 'cups', 'pantry_staple', true, 'for frying'),
    ],
    steps: [
      'Mix rice flour, sugar, mashed banana, melted ghee, cardamom, and clove powder in a large bowl.',
      'Gradually add warm water or milk, mixing to form a thick, pourable batter (like pancake batter consistency).',
      'Cover and let rest for 30 minutes to 1 hour (or overnight for best results).',
      'Heat oil to 350°F (175°C) in a deep pan or kadhai.',
      'Take a handful of batter and shape it into a ring by squeezing through your fist, letting it drop into the hot oil in a circular motion.',
      'Fry on medium heat, flipping once, until golden brown on both sides (about 3-4 minutes total).',
      'Drain on paper towels. Serve warm or at room temperature.',
    ],
    variations: {
      adult: v(
        'Classic Sel Roti',
        'Crispy, lightly sweet festive rice bread',
        ['Serve with yogurt or achar', 'Enjoy with a cup of Nepali chiya (tea)', 'Drizzle with honey for extra sweetness'],
        [], null,
        'Best enjoyed warm and crispy — a true Nepali festival staple',
      ),
      kid: v(
        'Sweet Rice Rings',
        'Fun ring-shaped sweet bread kids love',
        ['Make smaller rings for little hands', 'The banana makes them naturally sweet', 'Serve with a small cup of warm milk'],
        [], null,
        'Kids love the ring shape — let them pick up and bite right in',
      ),
      toddler: v(
        'Soft Rice Ring Pieces',
        'Bite-sized pieces of soft sweet bread',
        ['Make thicker rings for softer centers', 'Break into small, manageable pieces', 'Choose the softest center parts'],
        ['Break into small pieces — avoid whole rings', 'The outer crust can be hard for toddlers', 'Supervise closely'],
        'Soft interior pieces only — skip very crispy outer bits',
        'Sel roti softens quickly when dipped in warm milk',
      ),
      baby: v(
        'Rice Banana Porridge',
        'Smooth rice flour porridge inspired by sel roti flavors',
        ['Cook rice flour with water into a smooth porridge', 'Mix in mashed banana', 'A tiny pinch of cardamom for flavor', 'No sugar, no frying'],
        ['No added sugar for babies', 'No fried food for babies', 'No honey', 'Supervise all eating'],
        'Smooth porridge consistency',
        'The banana and cardamom combination introduces Nepali flavors gently',
      ),
    },
    leftoverTip: 'Store in an airtight container for 2-3 days. Reheat briefly in oven to restore crispiness.',
    keyIngredients: ['rice flour', 'banana', 'sugar', 'cardamom', 'ghee'],
    relatedTerms: ['sel roti', 'selroti', 'nepali bread', 'rice bread', 'festival food', 'dashain', 'tihar', 'ring bread'],
  },

  // ─── 6. Thukpa (Nepali Noodle Soup) ───────────────────────
  {
    id: 'nepali-thukpa',
    title: 'Thukpa',
    tagline: 'Warming Himalayan noodle soup for cold days and cozy nights',
    description: 'A hearty Tibetan-inspired noodle soup popular throughout Nepal. Loaded with vegetables, tender noodles, and a fragrant ginger-garlic broth that warms you to the core.',
    cuisineTags: ['nepali', 'asian'],
    proteinType: 'chicken',
    prepTime: 15,
    cookTime: 25,
    estimatedCost: 9,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['soup', 'noodles', 'comfort', 'warming', 'one-pot', 'high-protein'],
    kidFriendlyScore: 8,
    dietaryCompat: ['nut-free', 'dairy-free'],
    ingredients: [
      ing('egg noodles or thukpa noodles', '8', 'oz', 'grain'),
      ing('chicken breast', '1/2', 'lb', 'protein', false, 'thinly sliced'),
      ing('carrot', '1', 'medium', 'produce', false, 'julienned'),
      ing('cabbage', '1', 'cup', 'produce', false, 'shredded'),
      ing('green onion', '3', 'stalks', 'produce'),
      ing('garlic', '4', 'cloves', 'produce'),
      ing('ginger', '1', 'inch piece', 'produce'),
      ing('soy sauce', '2', 'tbsp', 'condiment', true),
      ing('chili flakes', '1/2', 'tsp', 'spice', true),
      ing('turmeric', '1/4', 'tsp', 'spice', true),
      ing('chicken broth', '6', 'cups', 'pantry_staple'),
      ing('oil', '1', 'tbsp', 'pantry_staple', true),
      ing('cilantro', '2', 'tbsp', 'produce', false, 'for garnish'),
      ing('lime', '1', '', 'produce', false, 'wedges for serving'),
    ],
    steps: [
      'Cook noodles according to package. Drain, rinse with cold water, and set aside.',
      'Heat oil in a large pot. Add minced garlic and ginger, sauté 1 minute.',
      'Add sliced chicken. Cook 4-5 minutes until no longer pink.',
      'Add carrots and cabbage. Stir-fry 2 minutes.',
      'Pour in chicken broth. Add soy sauce, turmeric, and chili flakes.',
      'Bring to a boil, then simmer for 15 minutes until vegetables are tender.',
      'Divide cooked noodles into bowls. Ladle hot soup over the noodles.',
      'Garnish with sliced green onions, cilantro, and a lime wedge.',
    ],
    variations: {
      adult: v(
        'Spicy Chicken Thukpa',
        'Fiery noodle soup with extra chili',
        ['Add extra chili oil or flakes', 'Top with a soft-boiled egg', 'Squeeze lime juice for brightness'],
        [], null,
        'Slurp the noodles — it\'s not just allowed, it\'s expected',
      ),
      kid: v(
        'Mild Chicken Noodle Soup',
        'Gentle, nourishing noodle soup',
        ['Skip chili flakes entirely', 'Cut noodles into shorter lengths', 'Use less soy sauce for lower sodium'],
        [], null,
        'Kids love slurping noodles — provide a deep spoon',
      ),
      toddler: v(
        'Soft Noodle Soup Bites',
        'Short, soft noodles in mild broth',
        ['Cook noodles extra soft', 'Cut into very short pieces', 'Shred chicken very finely', 'Skip chili and reduce soy sauce'],
        ['Cut noodles short to prevent choking', 'Shred chicken into tiny pieces', 'Cool before serving'],
        'Very soft, short noodles with finely shredded chicken',
        'A warm bowl is perfect for toddlers on cold days',
      ),
      baby: v(
        'Chicken Veggie Broth with Soft Noodles',
        'Mild broth with overcooked noodle bits',
        ['Overcook a small portion of noodles until very soft', 'Mash or cut into tiny pieces', 'Use plain low-sodium broth', 'Shred chicken very fine or blend', 'Skip soy sauce and chili'],
        ['No soy sauce for young babies', 'No salt', 'Ensure noodles are very soft', 'Supervise all eating'],
        'Mashed soft noodles for 9-12mo. Under 9mo, offer just the broth with chicken purée.',
        'The warm ginger broth is soothing and gentle on baby tummies',
      ),
    },
    simplifiedSteps: [
      'Cook noodles. In the same pot, sauté garlic and ginger, add sliced chicken.',
      'Add broth, vegetables, and soy sauce. Simmer 15 min.',
      'Add noodles back in. Serve with lime wedge.',
    ],
    leftoverTip: 'Store noodles separately from broth to prevent mushiness. Good for 2 days.',
    keyIngredients: ['noodles', 'chicken', 'ginger', 'garlic', 'cabbage', 'soy sauce'],
    relatedTerms: ['thukpa', 'nepali noodle soup', 'himalayan soup', 'tibetan noodle soup', 'noodle soup'],
  },

  // ─── 7. Chatamari (Nepali Rice Crepe) ─────────────────────
  {
    id: 'nepali-chatamari',
    title: 'Chatamari',
    tagline: 'Crispy Newari rice crepe — Nepal\'s answer to pizza',
    description: 'A thin, crispy rice flour crepe topped with spiced minced meat, egg, and vegetables. A beloved Newari specialty often called Nepali pizza for its flat, topped presentation.',
    cuisineTags: ['nepali'],
    proteinType: 'eggs',
    prepTime: 15,
    cookTime: 20,
    estimatedCost: 8,
    costLevel: 'low',
    servings: 4,
    difficulty: 'moderate',
    energyDemand: 'medium',
    tags: ['crepe', 'street-food', 'newari', 'gluten-free', 'crispy'],
    kidFriendlyScore: 7,
    dietaryCompat: ['gluten-free', 'nut-free'],
    ingredients: [
      ing('rice flour', '1.5', 'cups', 'grain'),
      ing('water', '1', 'cup', 'other', true),
      ing('eggs', '4', '', 'protein'),
      ing('ground chicken or buff', '1/2', 'lb', 'protein', false, 'optional'),
      ing('onion', '1', 'medium', 'produce', false, 'finely diced'),
      ing('tomato', '1', 'small', 'produce', false, 'diced'),
      ing('green onion', '3', 'stalks', 'produce', false, 'sliced'),
      ing('cilantro', '2', 'tbsp', 'produce'),
      ing('cumin powder', '1/2', 'tsp', 'spice', true),
      ing('turmeric', '1/4', 'tsp', 'spice', true),
      ing('chili flakes', '1/4', 'tsp', 'spice', true),
      ing('salt', '', 'to taste', 'spice', true),
      ing('oil', '2', 'tbsp', 'pantry_staple', true),
    ],
    steps: [
      'Mix rice flour with water to make a smooth, thin batter (like crepe batter). Let rest 15 minutes.',
      'If using meat: sauté ground meat with onion, cumin, turmeric, and salt until cooked through. Set aside.',
      'Heat a flat pan or tawa on medium heat. Lightly oil it.',
      'Pour a thin layer of rice batter onto the pan, spreading in a circular motion.',
      'Immediately crack an egg on top and spread it gently over the crepe.',
      'Sprinkle cooked meat (if using), diced tomato, green onion, and cilantro on top.',
      'Cover and cook on medium-low for 4-5 minutes until the edges are crispy and the bottom is golden.',
      'Slide off carefully. Cut into wedges and serve hot.',
    ],
    variations: {
      adult: v(
        'Classic Chatamari',
        'Crispy rice crepe with egg and meat topping',
        ['Add extra chili flakes', 'Top with pickled onion', 'Serve with tomato achar on the side'],
        [], null,
        'Eat fresh off the pan — the crispiness is everything',
      ),
      kid: v(
        'Cheesy Rice Pizza',
        'Mild crepe with egg and veggies',
        ['Skip chili', 'Add shredded cheese on top', 'Call it "Nepali pizza" — kids will be intrigued'],
        [], null,
        'Cut into small pizza-like triangles for fun eating',
      ),
      toddler: v(
        'Soft Rice Egg Pancake',
        'Tender, soft rice flour pancake with egg',
        ['Make smaller, thicker pancakes (less crispy, more soft)', 'Just egg topping, no meat', 'Skip all spices except a pinch of turmeric', 'Cut into small strips'],
        ['Cut into manageable finger-food strips', 'Ensure egg is fully cooked', 'Cool before serving'],
        'Soft, tender pancake strips — not too crispy',
        'Great finger food for practicing self-feeding',
      ),
      baby: v(
        'Rice Flour Egg Pancake Strips',
        'Soft, plain rice flour pancake for self-feeding',
        ['Make a thick, soft pancake with just rice flour, water, and a beaten egg', 'Cook until soft (not crispy)', 'Cut into thin strips', 'No salt or spices'],
        ['Ensure egg is fully cooked', 'No salt', 'Cut into safe finger-food strips', 'Supervise all eating'],
        'Soft strips that dissolve easily — not crispy',
        'Great for baby-led weaning — easy to grip and gum',
      ),
    },
    leftoverTip: 'Best eaten fresh. Reheat in a dry pan to restore some crispiness.',
    keyIngredients: ['rice flour', 'egg', 'onion', 'tomato', 'cumin'],
    relatedTerms: ['chatamari', 'nepali pizza', 'rice crepe', 'newari food', 'chataamari', 'rice pancake'],
  },

  // ─── 8. Kwati (Mixed Bean Soup) ───────────────────────────
  {
    id: 'nepali-kwati',
    title: 'Kwati',
    tagline: 'Nine-bean sprouted soup — a Nepali powerhouse of nutrition',
    description: 'A rich, hearty soup made from nine types of sprouted beans, traditionally prepared during Janai Purnima festival. Packed with plant protein and incredibly nourishing.',
    cuisineTags: ['nepali'],
    proteinType: 'beans',
    prepTime: 20,
    cookTime: 45,
    estimatedCost: 8,
    costLevel: 'low',
    servings: 6,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['soup', 'vegetarian', 'vegan', 'high-protein', 'iron-rich', 'traditional', 'gluten-free', 'festive'],
    kidFriendlyScore: 5,
    dietaryCompat: ['vegetarian', 'vegan', 'gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('mixed sprouted beans', '3', 'cups', 'protein', false, 'black-eyed peas, chickpeas, mung beans, kidney beans, soybeans etc.'),
      ing('onion', '2', 'medium', 'produce'),
      ing('tomato', '2', 'medium', 'produce'),
      ing('garlic', '6', 'cloves', 'produce'),
      ing('ginger', '2', 'inch piece', 'produce'),
      ing('turmeric', '1/2', 'tsp', 'spice', true),
      ing('cumin seeds', '1', 'tsp', 'spice', true),
      ing('coriander powder', '1', 'tsp', 'spice', true),
      ing('green chili', '2', '', 'produce'),
      ing('mustard oil', '2', 'tbsp', 'pantry_staple'),
      ing('jimbu (Himalayan herb)', '1', 'tsp', 'spice', false, 'optional — adds authentic smoky aroma'),
      ing('salt', '', 'to taste', 'spice', true),
      ing('cilantro', '3', 'tbsp', 'produce', false, 'for garnish'),
      ing('water', '8', 'cups', 'other', true),
    ],
    steps: [
      'If beans aren\'t pre-sprouted: soak mixed beans overnight. Drain and keep in a damp cloth for 1-2 days until sprouted.',
      'Heat mustard oil in a large pot. Add cumin seeds and jimbu (if using). Let sizzle.',
      'Add chopped onion, garlic, and ginger. Sauté 4 minutes until golden.',
      'Add diced tomatoes, green chilies, turmeric, and coriander powder. Cook 3 minutes.',
      'Add all sprouted beans and 8 cups water. Bring to a boil.',
      'Reduce heat and simmer covered for 40-45 minutes, until all beans are completely tender.',
      'Season with salt. Garnish with fresh cilantro.',
      'Serve hot in bowls as a protein-rich soup or alongside rice.',
    ],
    variations: {
      adult: v(
        'Traditional Kwati',
        'Hearty nine-bean soup with bold spicing',
        ['Extra green chili and a splash of lemon juice', 'Garnish with crispy fried garlic chips', 'Serve with rice and a side of gundruk'],
        [], null,
        'Kwati is best eaten on Janai Purnima — but delicious any day of the year',
      ),
      kid: v(
        'Mild Bean Soup',
        'Gentle mixed bean soup with soft beans',
        ['Skip green chili', 'Use fewer bean varieties if some are too firm', 'Blend partially for a creamier texture'],
        [], null,
        'Serve with rice or bread for dipping',
      ),
      toddler: v(
        'Creamy Bean Blend',
        'Blended mixed bean soup — smooth and protein-rich',
        ['Blend most of the soup for smooth texture', 'Leave a few soft whole beans for texture practice', 'Skip chili and reduce spices'],
        ['Ensure all beans are very soft', 'Watch for any firm bean skins', 'Test temperature'],
        'Mostly smooth with a few soft whole beans',
        'An excellent plant-protein meal for growing toddlers',
      ),
      baby: v(
        'Mixed Bean Purée',
        'Smooth, protein-packed bean purée',
        ['Cook beans until extremely soft', 'Blend completely smooth', 'No salt, no chili', 'Add breast milk or formula for thinner consistency'],
        ['Ensure completely smooth — bean skins can be a choking hazard', 'No salt', 'Introduce one bean type at a time for allergy monitoring'],
        'Completely smooth purée for 6-8mo, slightly textured for 9-12mo',
        'Introduce beans gradually — they\'re an important iron source',
      ),
    },
    leftoverTip: 'Freezes beautifully for up to 3 months. Thickens as it cools — add water when reheating.',
    keyIngredients: ['sprouted beans', 'garlic', 'ginger', 'turmeric', 'mustard oil'],
    relatedTerms: ['kwati', 'quati', 'nine bean soup', 'sprouted bean soup', 'janai purnima', 'nepali bean soup'],
  },

  // ─── 9. Sekuwa (Nepali Grilled Meat) ─────────────────────
  {
    id: 'nepali-sekuwa',
    title: 'Sekuwa',
    tagline: 'Smoky charcoal-grilled spiced meat — Nepal\'s BBQ classic',
    description: 'Tender chunks of marinated meat grilled over charcoal until smoky and caramelized. A staple at Nepali gatherings and street corners, served with beaten rice (chiura) and fresh onion rings.',
    cuisineTags: ['nepali'],
    proteinType: 'chicken',
    prepTime: 30,
    cookTime: 15,
    estimatedCost: 11,
    costLevel: 'medium',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'medium',
    tags: ['grilled', 'bbq', 'high-protein', 'gluten-free', 'party-food', 'street-food'],
    kidFriendlyScore: 7,
    dietaryCompat: ['gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('chicken thighs (boneless)', '1.5', 'lbs', 'protein', false, 'cut into 1.5-inch cubes'),
      ing('yogurt', '3', 'tbsp', 'dairy', false, 'for marinade'),
      ing('garlic paste', '1', 'tbsp', 'produce'),
      ing('ginger paste', '1', 'tbsp', 'produce'),
      ing('cumin powder', '1', 'tsp', 'spice', true),
      ing('coriander powder', '1', 'tsp', 'spice', true),
      ing('turmeric', '1/2', 'tsp', 'spice', true),
      ing('chili powder', '1', 'tsp', 'spice', true),
      ing('timur (Sichuan pepper)', '1/2', 'tsp', 'spice', false, 'crushed'),
      ing('mustard oil', '2', 'tbsp', 'pantry_staple'),
      ing('lemon juice', '1', 'tbsp', 'condiment'),
      ing('salt', '1', 'tsp', 'spice', true),
      ing('beaten rice (chiura)', '2', 'cups', 'grain', false, 'for serving'),
      ing('onion', '1', 'large', 'produce', false, 'sliced into rings'),
    ],
    steps: [
      'Combine yogurt, garlic paste, ginger paste, cumin, coriander, turmeric, chili powder, crushed timur, mustard oil, lemon juice, and salt.',
      'Toss chicken cubes in the marinade. Cover and refrigerate at least 2 hours (overnight is best).',
      'Thread marinated chicken onto skewers.',
      'Grill over charcoal or on a grill pan on high heat for 12-15 minutes, turning occasionally, until charred and cooked through.',
      'Serve immediately with beaten rice (chiura), raw onion rings, and a squeeze of lemon.',
    ],
    variations: {
      adult: v(
        'Spicy Chicken Sekuwa',
        'Smoky, spiced grilled chicken with charred edges',
        ['Extra chili and timur for serious heat and numbing', 'Serve with tongba (millet beer) for the full Nepali experience', 'Add a side of tomato achar'],
        [], null,
        'The smokier the char, the better — don\'t be afraid of those blackened edges',
      ),
      kid: v(
        'Mild Grilled Chicken Bites',
        'Tender grilled chicken with yogurt marinade',
        ['Skip chili powder and timur', 'Cut into smaller bite-size pieces', 'Grill until well-done but still juicy'],
        [], null,
        'Serve on small sticks — eating off skewers is always fun for kids',
      ),
      toddler: v(
        'Soft Grilled Chicken Shreds',
        'Tender, mild yogurt-marinated chicken',
        ['Skip all chili and timur', 'Use chicken thigh for tenderness', 'Cook thoroughly and shred into small pieces', 'The yogurt marinade keeps it soft'],
        ['Shred into small, manageable pieces', 'Ensure fully cooked (165°F)', 'Let cool before serving'],
        'Soft, shredded chicken — yogurt marinade helps keep it tender',
        'Chicken thigh stays moist and is easier for toddlers to chew',
      ),
      baby: v(
        'Yogurt Chicken Purée',
        'Mild yogurt-marinated chicken, puréed smooth',
        ['Marinate with just yogurt, a tiny bit of garlic and ginger', 'Grill or bake until cooked through', 'Blend with a little broth until smooth', 'No salt, no chili'],
        ['No spicy seasonings', 'Ensure fully cooked', 'Blend to appropriate texture', 'Supervise all eating'],
        'Smooth purée for 6-8mo, fine shreds for 9-12mo',
        'Yogurt-marinated chicken is incredibly tender for babies',
      ),
    },
    leftoverTip: 'Reheat on a hot pan for 2 minutes per side to restore the char. Stores 3 days refrigerated.',
    keyIngredients: ['chicken', 'yogurt', 'garlic', 'ginger', 'cumin', 'timur'],
    relatedTerms: ['sekuwa', 'sikuwa', 'nepali bbq', 'grilled meat', 'nepali grill', 'charcoal meat'],
  },

  // ─── 10. Choila (Spiced Grilled Meat Salad) ──────────────
  {
    id: 'nepali-choila',
    title: 'Choila',
    tagline: 'Fiery spiced grilled meat salad — a bold Newari delicacy',
    description: 'Chargrilled meat hand-shredded and tossed with mustard oil, chili, ginger, garlic, and fresh herbs. A Newari festival favorite that\'s intensely flavorful and addictively spicy.',
    cuisineTags: ['nepali'],
    proteinType: 'chicken',
    prepTime: 20,
    cookTime: 15,
    estimatedCost: 10,
    costLevel: 'medium',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['salad', 'spicy', 'newari', 'high-protein', 'gluten-free', 'no-cook-assembly'],
    kidFriendlyScore: 4,
    dietaryCompat: ['gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('chicken breast', '1', 'lb', 'protein'),
      ing('mustard oil', '2', 'tbsp', 'pantry_staple'),
      ing('garlic', '4', 'cloves', 'produce', false, 'finely minced'),
      ing('ginger', '1', 'tbsp', 'produce', false, 'finely grated'),
      ing('green chili', '3', '', 'produce', false, 'finely chopped'),
      ing('timur (Sichuan pepper)', '1/2', 'tsp', 'spice', false, 'crushed'),
      ing('cumin powder', '1/2', 'tsp', 'spice', true),
      ing('chili powder', '1', 'tsp', 'spice', true),
      ing('turmeric', '1/4', 'tsp', 'spice', true),
      ing('lemon juice', '2', 'tbsp', 'condiment'),
      ing('red onion', '1', 'small', 'produce', false, 'thinly sliced'),
      ing('cilantro', '3', 'tbsp', 'produce', false, 'chopped'),
      ing('salt', '', 'to taste', 'spice', true),
    ],
    steps: [
      'Grill chicken breast over charcoal or on a grill pan until charred and fully cooked (about 6-7 min per side).',
      'Let rest 5 minutes, then shred or chop into small bite-sized pieces.',
      'In a bowl, combine mustard oil, minced garlic, grated ginger, green chili, crushed timur, cumin, chili powder, turmeric, lemon juice, and salt.',
      'Add the shredded chicken to the spice mixture. Toss well to coat every piece.',
      'Add sliced red onion and chopped cilantro. Mix gently.',
      'Let marinate for 10 minutes before serving for flavors to meld.',
      'Serve with beaten rice (chiura) or as part of a Newari feast.',
    ],
    variations: {
      adult: v(
        'Spicy Chicken Choila',
        'Fiery shredded grilled chicken salad',
        ['Increase green chili and timur for maximum heat', 'Best with beaten rice and a cold beverage', 'Add roasted tomato on the side'],
        [], null,
        'The mustard oil kick combined with timur numbing heat is what makes choila special',
      ),
      kid: v(
        'Mild Chicken Salad Bites',
        'Gentle seasoned shredded chicken',
        ['Skip all chili, timur, and mustard oil', 'Use olive oil instead', 'Add a little honey for sweetness', 'Mix with rice'],
        [], null,
        'Serve shredded chicken mixed with rice for easy eating',
      ),
      toddler: v(
        'Soft Shredded Chicken',
        'Tender, mildly seasoned chicken shreds',
        ['Skip all spicy ingredients', 'Use very finely shredded chicken', 'Mix with a tiny bit of oil and lemon juice only', 'Serve with soft rice'],
        ['Shred chicken very finely', 'No spicy seasonings', 'Test temperature'],
        'Finely shredded, tender chicken',
        'Grilled chicken thigh works better — it stays more tender',
      ),
      baby: v(
        'Plain Grilled Chicken Purée',
        'Smooth chicken purée from grilled chicken',
        ['Grill plain chicken (no marinade)', 'Blend with broth until smooth', 'A tiny bit of ghee for calories'],
        ['No spices for young babies', 'No salt', 'Blend thoroughly', 'Supervise all eating'],
        'Smooth purée for 6-8mo, fine shreds for 9-12mo',
        'Grilling gives chicken a lovely smoky flavor babies often enjoy',
      ),
    },
    leftoverTip: 'Stores 2 days refrigerated. Flavors intensify overnight. Serve cold or at room temperature.',
    keyIngredients: ['chicken', 'mustard oil', 'garlic', 'ginger', 'timur', 'chili'],
    relatedTerms: ['choila', 'chhoyela', 'chhoila', 'newari food', 'nepali salad', 'grilled meat salad'],
  },

  // ─── 11. Bara (Nepali Lentil Patty) ──────────────────────
  {
    id: 'nepali-bara',
    title: 'Bara',
    tagline: 'Crispy lentil patties — Newari street food at its finest',
    description: 'Savory pan-fried patties made from ground black lentil batter, often topped with an egg or minced meat. Crispy outside, fluffy inside — a Newari celebration essential.',
    cuisineTags: ['nepali'],
    proteinType: 'lentils',
    prepTime: 25,
    cookTime: 20,
    estimatedCost: 6,
    costLevel: 'low',
    servings: 4,
    difficulty: 'moderate',
    energyDemand: 'medium',
    tags: ['snack', 'street-food', 'newari', 'high-protein', 'gluten-free', 'vegetarian'],
    kidFriendlyScore: 7,
    dietaryCompat: ['vegetarian', 'gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('black lentils (urad dal)', '1', 'cup', 'protein', false, 'soaked overnight'),
      ing('ginger', '1', 'inch piece', 'produce'),
      ing('garlic', '3', 'cloves', 'produce'),
      ing('cumin seeds', '1/2', 'tsp', 'spice', true),
      ing('turmeric', '1/4', 'tsp', 'spice', true),
      ing('green chili', '1', '', 'produce', false, 'optional'),
      ing('salt', '1/2', 'tsp', 'spice', true),
      ing('eggs', '4', '', 'protein', false, 'optional — for egg bara'),
      ing('oil', '3', 'tbsp', 'pantry_staple', true, 'for pan-frying'),
    ],
    steps: [
      'Drain soaked lentils. Grind in a blender with ginger, garlic, green chili (if using), cumin, turmeric, and salt. Add minimal water — batter should be thick like pancake batter.',
      'Let batter rest 15 minutes.',
      'Heat oil in a flat pan or tawa on medium heat.',
      'Pour a ladleful of batter and spread into a round patty shape (about 3-4 inches).',
      'For egg bara: crack an egg on top of the patty as it cooks.',
      'Cook until the bottom is golden and crispy (about 3-4 minutes), then flip.',
      'Cook the other side until golden (2-3 minutes). Remove and drain on paper towels.',
      'Serve hot with tomato achar or as part of a Newari feast plate (samay baji).',
    ],
    variations: {
      adult: v(
        'Egg Bara',
        'Crispy lentil patty topped with a fried egg',
        ['Top with egg for protein boost', 'Serve with spicy tomato achar', 'Add minced meat topping for non-veg version'],
        [], null,
        'The crispy edges with the soft egg on top is perfection',
      ),
      kid: v(
        'Lentil Mini Patties',
        'Mild, crispy lentil patties kids enjoy',
        ['Skip green chili', 'Make smaller patties for kid-sized portions', 'Serve with ketchup if achar is too spicy'],
        [], null,
        'Tell them they\'re Nepali pancakes — the crispy texture is fun',
      ),
      toddler: v(
        'Soft Lentil Cakes',
        'Tender, mild lentil patties',
        ['Make small, thick patties for softer centers', 'Skip chili and reduce spices', 'Cook on lower heat for softer texture', 'No egg topping needed'],
        ['Cut into small pieces', 'Ensure center is cooked through', 'Cool before serving'],
        'Thick, soft patties — crispy outside but fluffy inside',
        'Excellent finger food — easy to hold and bite',
      ),
      baby: v(
        'Lentil Purée Patties',
        'Super-soft lentil cakes for self-feeding',
        ['Make very thick batter for softer result', 'Minimal seasoning — just turmeric', 'Cook on low heat until very soft', 'Mash or cut into thin strips'],
        ['No salt for young babies', 'Ensure very soft texture', 'Cut into safe sizes', 'Supervise all eating'],
        'Very soft, almost melt-in-mouth texture',
        'Black lentils are iron-rich — great for babies over 8 months',
      ),
    },
    leftoverTip: 'Reheat in a dry pan to restore crispiness. Stores 2 days refrigerated.',
    keyIngredients: ['black lentils', 'ginger', 'garlic', 'cumin', 'egg'],
    relatedTerms: ['bara', 'wo', 'baara', 'lentil patty', 'newari food', 'nepali pancake', 'urad dal patty'],
  },

  // ─── 12. Yomari (Sweet Dumpling) ──────────────────────────
  {
    id: 'nepali-yomari',
    title: 'Yomari',
    tagline: 'Sweet rice flour dumplings with molasses filling — a Newari treasure',
    description: 'Fish-shaped steamed rice flour dumplings filled with a warm, gooey chaku (molasses) and sesame filling. Made during Yomari Punhi festival, these are Nepal\'s most beloved sweet treat.',
    cuisineTags: ['nepali'],
    proteinType: 'none',
    prepTime: 40,
    cookTime: 15,
    estimatedCost: 6,
    costLevel: 'low',
    servings: 4,
    difficulty: 'hard',
    energyDemand: 'high',
    tags: ['dessert', 'sweet', 'festive', 'steamed', 'newari', 'traditional', 'vegetarian'],
    kidFriendlyScore: 8,
    dietaryCompat: ['vegetarian', 'nut-free', 'dairy-free', 'gluten-free'],
    ingredients: [
      ing('rice flour', '2', 'cups', 'grain'),
      ing('water', '1', 'cup', 'other', true, 'hot'),
      ing('chaku (molasses/jaggery)', '1/2', 'cup', 'pantry_staple', false, 'grated or chopped'),
      ing('sesame seeds', '2', 'tbsp', 'spice', false, 'toasted'),
      ing('coconut', '2', 'tbsp', 'produce', false, 'freshly grated, optional'),
      ing('cardamom powder', '1/4', 'tsp', 'spice'),
    ],
    steps: [
      'Gradually add hot water to rice flour, mixing and kneading into a smooth, pliable dough. Cover and rest 10 minutes.',
      'Prepare the filling: warm chaku until soft, mix with toasted sesame seeds, coconut, and cardamom.',
      'Take a small ball of dough and shape it into a cone/cup by pressing your thumb into the center.',
      'Fill the cone with the chaku mixture (about 1 tbsp).',
      'Pinch and seal the top into the traditional fig/fish shape, creating a pointed tip.',
      'Repeat with remaining dough and filling.',
      'Steam yomari over boiling water for 12-15 minutes until the dough is translucent and cooked.',
      'Serve warm — the filling should be melted and gooey inside.',
    ],
    variations: {
      adult: v(
        'Classic Yomari',
        'Traditional sweet dumplings with warm molasses center',
        ['Serve warm for the gooey center experience', 'Pair with Nepali milk tea', 'Try a khuwa (milk solid) filling variation'],
        [], null,
        'Bite off the tip and let the sweet filling flow — the traditional way to eat yomari',
      ),
      kid: v(
        'Sweet Rice Dumplings',
        'Fun-shaped sweet dumplings with gooey filling',
        ['Let kids help shape the dumplings', 'The fish shape is fun for children', 'Ensure filling is not too hot when served'],
        [], null,
        'Make it a fun activity — kids love shaping the dough',
      ),
      toddler: v(
        'Sweet Rice Balls',
        'Simple sweet rice dough balls with mild filling',
        ['Make smaller, round shapes (skip the complex fish shape)', 'Use less filling to prevent mess', 'Cut in half before serving so they can see the filling'],
        ['Cut in half to prevent choking', 'Ensure not too hot — molasses retains heat', 'The filling is sticky — supervise closely'],
        'Soft, slightly sticky dough with warm sweet center',
        'Half-portions are perfect for toddler-sized bites',
      ),
      baby: v(
        'Sweet Rice Porridge',
        'Warm rice flour porridge with a hint of sweetness',
        ['Cook rice flour into a smooth porridge', 'Add a tiny amount of jaggery for sweetness (over 12 months)', 'A pinch of cardamom', 'No sesame for allergen reasons if not yet introduced'],
        ['No honey', 'Minimal sweetener for babies', 'Check sesame allergy', 'Supervise all eating'],
        'Smooth, warm porridge',
        'A gentle introduction to Nepali festive flavors',
      ),
    },
    leftoverTip: 'Best eaten fresh. Reheat by steaming for 3-4 minutes — microwaving makes them rubbery.',
    keyIngredients: ['rice flour', 'jaggery', 'sesame seeds', 'cardamom'],
    relatedTerms: ['yomari', 'yomari punhi', 'sweet dumpling', 'chaku', 'newari sweet', 'rice dumpling'],
  },

  // ─── 13. Dhido (Buckwheat/Millet Porridge) ────────────────
  {
    id: 'nepali-dhido',
    title: 'Dhido',
    tagline: 'Traditional Nepali buckwheat porridge — hearty mountain fuel',
    description: 'A thick, dough-like porridge made from buckwheat or millet flour, stirred over heat until firm. The traditional staple of Nepal\'s hill regions, served with gundruk soup and chutney.',
    cuisineTags: ['nepali'],
    proteinType: 'none',
    prepTime: 5,
    cookTime: 15,
    estimatedCost: 4,
    costLevel: 'low',
    servings: 4,
    difficulty: 'easy',
    energyDemand: 'low',
    tags: ['staple', 'traditional', 'gluten-free', 'vegan', 'budget-friendly', 'mountain-food'],
    kidFriendlyScore: 5,
    dietaryCompat: ['vegetarian', 'vegan', 'gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('buckwheat flour (or millet flour)', '2', 'cups', 'grain'),
      ing('water', '4', 'cups', 'other', true),
      ing('salt', '', 'pinch', 'spice', true),
      ing('ghee', '1', 'tbsp', 'dairy', false, 'for serving'),
    ],
    steps: [
      'Bring water to a rolling boil in a heavy-bottomed pot.',
      'Reduce heat to medium. Begin adding flour gradually while stirring vigorously with a wooden spatula (dabilo).',
      'Keep stirring continuously — this requires arm strength! The mixture will thicken significantly.',
      'Continue cooking and stirring for 8-10 minutes until the dhido pulls away cleanly from the sides of the pot.',
      'The dhido should be thick, smooth, and hold its shape when scooped.',
      'Serve hot on a plate with a dollop of ghee, alongside gundruk ko jhol, dal, and fresh chutney.',
    ],
    variations: {
      adult: v(
        'Classic Dhido',
        'Firm buckwheat porridge with dal and gundruk',
        ['Pinch pieces with your fingers and dip into dal', 'Serve with gundruk ko jhol and tomato achar', 'A drizzle of ghee makes it richer'],
        [], null,
        'Eat with your hands — tear off a piece, dip in dal, and enjoy',
      ),
      kid: v(
        'Soft Dhido Bites',
        'Slightly softer version shaped into fun bites',
        ['Make it slightly softer by using more water', 'Shape into small balls or fun shapes', 'Serve with mild dal for dipping'],
        [], null,
        'Shape into small balls — kids can dip them into dal like nuggets',
      ),
      toddler: v(
        'Creamy Dhido Porridge',
        'Softer, creamier version for little ones',
        ['Add extra water for a softer, porridge-like consistency', 'Mix in a little ghee for calories and smoothness', 'Serve warm with mild dal'],
        ['Ensure temperature is safe', 'Soft enough to gum easily'],
        'Soft, smooth porridge texture — not firm like adult version',
        'Buckwheat is naturally nutritious and easy to digest',
      ),
      baby: v(
        'Buckwheat Porridge',
        'Smooth buckwheat flour porridge for babies',
        ['Cook with extra water for thin, smooth consistency', 'Stir well to avoid lumps', 'No salt', 'Mix with breast milk or formula'],
        ['No salt', 'Ensure smooth and lump-free', 'Check for buckwheat tolerance', 'Supervise all eating'],
        'Thin, smooth porridge for 6-8mo, slightly thicker for 9-12mo',
        'Buckwheat is iron-rich and a great alternative to rice cereal',
      ),
    },
    leftoverTip: 'Dhido firms up when cold. Slice and pan-fry in ghee for a crispy next-day version.',
    keyIngredients: ['buckwheat flour', 'water', 'ghee'],
    relatedTerms: ['dhido', 'dhindo', 'buckwheat porridge', 'millet porridge', 'nepali porridge', 'mountain food'],
  },

  // ─── 14. Samay Baji (Newari Feast Plate) ──────────────────
  {
    id: 'nepali-samay-baji',
    title: 'Samay Baji',
    tagline: 'The iconic Newari ceremonial feast platter',
    description: 'A traditional Newari feast plate featuring beaten rice (chiura), marinated meat, black soybeans, egg, ginger, garlic pickle, and greens. A complete meal celebrating Newar culture.',
    cuisineTags: ['nepali'],
    proteinType: 'eggs',
    prepTime: 30,
    cookTime: 25,
    estimatedCost: 14,
    costLevel: 'medium',
    servings: 4,
    difficulty: 'moderate',
    energyDemand: 'medium',
    tags: ['feast', 'ceremonial', 'newari', 'high-protein', 'traditional', 'gluten-free'],
    kidFriendlyScore: 6,
    dietaryCompat: ['gluten-free', 'nut-free'],
    ingredients: [
      ing('beaten rice (chiura)', '3', 'cups', 'grain'),
      ing('black soybeans (bhatmas)', '1', 'cup', 'protein', false, 'soaked and boiled'),
      ing('eggs', '4', '', 'protein', false, 'hard-boiled'),
      ing('chicken', '1/2', 'lb', 'protein', false, 'for choila — see choila recipe'),
      ing('ginger', '2', 'inch piece', 'produce', false, 'sliced thin'),
      ing('garlic', '6', 'cloves', 'produce'),
      ing('green onion', '4', 'stalks', 'produce'),
      ing('spinach or mustard greens', '2', 'cups', 'produce', false, 'sautéed'),
      ing('dried red chili', '2', '', 'spice', true),
      ing('mustard oil', '2', 'tbsp', 'pantry_staple'),
      ing('turmeric', '1/2', 'tsp', 'spice', true),
      ing('salt', '', 'to taste', 'spice', true),
      ing('achar (pickle)', '4', 'tbsp', 'condiment', false, 'tomato or radish'),
    ],
    steps: [
      'Prepare beaten rice: soak chiura in water for 1 minute, drain well, and fluff.',
      'Boil black soybeans until tender (about 30 min if pre-soaked). Drain and toss with a little salt, turmeric, and mustard oil.',
      'Hard-boil eggs. Peel and halve.',
      'Prepare chicken choila: grill and shred chicken, toss with mustard oil, chili, garlic, ginger, and salt (see choila recipe).',
      'Sauté greens with garlic and a pinch of salt until wilted.',
      'Slice ginger into thin matchsticks (this is eaten as a palate cleanser).',
      'Arrange everything on a large plate: chiura in the center, surrounded by choila, soybeans, egg halves, sautéed greens, ginger slices, and achar.',
      'Serve communally — everyone eats from the shared plate traditionally.',
    ],
    variations: {
      adult: v(
        'Full Samay Baji Platter',
        'Complete Newari feast with all the trimmings',
        ['Add bara (lentil patty) to the plate', 'Include raw ginger slices as palate cleanser', 'Serve with local rice beer (aila) traditionally'],
        [], null,
        'Eat with your hands — mix chiura with different items each bite',
      ),
      kid: v(
        'Mini Feast Plate',
        'Kid-friendly selection from the platter',
        ['Mild choila (no chili)', 'Chiura, egg, and soybeans', 'Skip the spicy achar — offer ketchup', 'Include the sautéed greens'],
        [], null,
        'Let kids pick and choose from the different items',
      ),
      toddler: v(
        'Toddler Baji Plate',
        'Soft, mild selections for little ones',
        ['Soft chiura (soak a bit longer)', 'Mash boiled egg', 'Mash soybeans slightly', 'Well-cooked soft greens chopped small', 'No spicy elements'],
        ['Mash harder items', 'Cut egg into small pieces', 'No whole soybeans if choking risk'],
        'All items soft and cut small',
        'A great way to introduce variety — multiple flavors and textures',
      ),
      baby: v(
        'Baby Baji Bowl',
        'Mashed components from the feast plate',
        ['Mash soaked chiura with a fork', 'Mash egg yolk with a little water', 'Blend soybeans smooth', 'Purée cooked greens', 'No salt or spices'],
        ['No whole soybeans', 'No salt', 'Mash everything appropriately', 'Supervise all eating'],
        'Individual purées for 6-8mo, soft mashed mix for 9-12mo',
        'Offer each component separately for taste exploration',
      ),
    },
    leftoverTip: 'Components store separately for 2 days. Chiura doesn\'t reheat — just re-soak.',
    keyIngredients: ['beaten rice', 'black soybeans', 'egg', 'chicken', 'mustard oil', 'ginger'],
    relatedTerms: ['samay baji', 'samae baji', 'newari feast', 'newari food', 'chiura set', 'ceremonial plate'],
  },

  // ─── 15. Gorkhali Lamb Curry ──────────────────────────────
  {
    id: 'nepali-gorkhali-lamb',
    title: 'Gorkhali Lamb Curry',
    tagline: 'Bold, aromatic lamb curry from the Gorkha hills',
    description: 'A rich, deeply spiced lamb curry slow-cooked with tomatoes, onions, and a fragrant blend of Nepali spices. Tender fall-apart meat in a thick, glossy gravy — pure comfort.',
    cuisineTags: ['nepali'],
    proteinType: 'beef',
    prepTime: 20,
    cookTime: 60,
    estimatedCost: 16,
    costLevel: 'high',
    servings: 4,
    difficulty: 'moderate',
    energyDemand: 'low',
    tags: ['curry', 'slow-cook', 'high-protein', 'gluten-free', 'comfort', 'special-occasion'],
    kidFriendlyScore: 5,
    dietaryCompat: ['gluten-free', 'nut-free', 'dairy-free'],
    ingredients: [
      ing('lamb shoulder or leg', '1.5', 'lbs', 'protein', false, 'cut into 2-inch chunks'),
      ing('onion', '2', 'large', 'produce', false, 'finely sliced'),
      ing('tomato', '3', 'medium', 'produce', false, 'puréed'),
      ing('garlic', '6', 'cloves', 'produce'),
      ing('ginger', '2', 'inch piece', 'produce'),
      ing('cumin seeds', '1', 'tsp', 'spice', true),
      ing('coriander powder', '1', 'tbsp', 'spice', true),
      ing('turmeric', '1/2', 'tsp', 'spice', true),
      ing('chili powder', '1', 'tsp', 'spice', true),
      ing('garam masala', '1', 'tsp', 'spice'),
      ing('timur (Sichuan pepper)', '1/2', 'tsp', 'spice'),
      ing('bay leaves', '2', '', 'spice', true),
      ing('cinnamon stick', '1', '', 'spice'),
      ing('mustard oil or ghee', '3', 'tbsp', 'pantry_staple'),
      ing('salt', '', 'to taste', 'spice', true),
      ing('cilantro', '3', 'tbsp', 'produce', false, 'for garnish'),
    ],
    steps: [
      'Heat mustard oil or ghee in a heavy pot. Add cumin seeds, bay leaves, and cinnamon stick. Sizzle 15 seconds.',
      'Add sliced onions. Cook on medium-high heat for 8-10 minutes until deeply golden brown.',
      'Add garlic-ginger paste. Sauté 2 minutes until fragrant.',
      'Add turmeric, coriander, chili powder, and crushed timur. Stir for 1 minute.',
      'Add puréed tomatoes. Cook 5 minutes until oil separates from the masala.',
      'Add lamb pieces. Sear on high heat for 3-4 minutes, turning to coat with the masala.',
      'Add 1 cup water. Bring to a boil, then reduce to a low simmer. Cover tightly.',
      'Cook for 50-60 minutes until lamb is fork-tender and the gravy is thick and rich.',
      'Finish with garam masala. Garnish with cilantro. Serve with steamed rice or dhido.',
    ],
    variations: {
      adult: v(
        'Gorkhali Khasi Ko Masu',
        'Rich, bold lamb curry with complex spicing',
        ['Extra timur for that signature numbing heat', 'Serve with rice and a side of fresh radish pickle', 'Even better reheated the next day'],
        [], null,
        'Slow cooking is key — don\'t rush the lamb. It should fall apart at the touch of a fork',
      ),
      kid: v(
        'Mild Lamb Stew',
        'Tender lamb in a gentle, mild sauce',
        ['Skip chili powder and timur', 'Use less spice overall', 'The slow-cooked lamb is naturally tender and kid-friendly', 'Serve shredded over rice'],
        [], null,
        'Shred the tender lamb into the rice — kids love the soft texture',
      ),
      toddler: v(
        'Soft Lamb & Rice',
        'Fork-tender lamb shredded into mild sauce with rice',
        ['Shred lamb very finely', 'Minimal spice — just turmeric and a little cumin', 'Mix shredded lamb into soft rice with some gravy'],
        ['Shred all lamb — no chunks', 'Remove any bone fragments', 'Ensure gravy is not too spicy'],
        'Very finely shredded, tender lamb in mild gravy',
        'Lamb shoulder becomes incredibly soft when slow-cooked — perfect for toddlers',
      ),
      baby: v(
        'Lamb Purée',
        'Smooth, iron-rich lamb purée',
        ['Use a small portion of plain slow-cooked lamb', 'Blend with cooking liquid until smooth', 'Add a small amount of cooked rice for texture', 'Minimal seasoning — turmeric only'],
        ['Blend very smooth for young babies', 'No salt', 'Ensure no bone fragments', 'Supervise all eating'],
        'Smooth purée for 6-8mo, soft shreds with rice for 9-12mo',
        'Lamb is an excellent source of iron and zinc for babies',
      ),
    },
    leftoverTip: 'Tastes significantly better the next day. Stores 4 days refrigerated, freezes well for 3 months.',
    keyIngredients: ['lamb', 'onion', 'tomato', 'garlic', 'ginger', 'timur', 'garam masala'],
    relatedTerms: ['gorkhali lamb', 'khasi ko masu', 'nepali mutton', 'lamb curry', 'nepali curry', 'mountain curry'],
  },
]
