import type { AIGeneratedPlan } from '@/types';

// ─────────────────────────────────────────────────────────────
// Demo Household: The Garcia-Chen Family
//   • Maya Garcia (mom, adult, PCOS + high-protein)
//   • Sam Chen (dad, adult, hypertension)
//   • Leo Garcia-Chen (toddler, 3yo, egg allergy, picky)
//   • Ava Garcia-Chen (baby, 9mo)
//   • Noah Garcia-Chen (kid, 8yo, school lunch, no spicy)
// ─────────────────────────────────────────────────────────────

// Demo data uses legacy member_variation fields — cast to satisfy strict type check
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const DEMO_WEEKLY_PLAN: AIGeneratedPlan = ({
  week_start: '2025-01-20',
  week_end: '2025-01-26',
  household_id: 'demo-household',
  total_estimated_cost: 145.5,
  servings_count: 5,
  dietary_summary: 'PCOS-friendly, low-sodium, egg-free, baby-safe, school-lunch ready',
  days: [
    // ── MONDAY ────────────────────────────────────────────────
    {
      date: '2025-01-20',
      day_of_week: 0,
      meals: [
        {
          id: 'meal-mon-breakfast',
          name: 'Peanut Butter Banana Oat Bowls',
          type: 'breakfast',
          cuisine_type: 'American',
          estimated_prep_time: 10,
          estimated_cook_time: 5,
          estimated_cost: 4.2,
          servings: 5,
          calorie_estimate: 340,
          image_prompt: 'warm oatmeal bowl with banana slices, drizzle of peanut butter, on a bright breakfast table',
          base_recipe: {
            description: 'Creamy rolled oats cooked with oat milk, topped with banana slices and a drizzle of peanut butter.',
            steps: [
              'Bring 2½ cups oat milk + 2½ cups water to a gentle boil',
              'Add 2 cups rolled oats, cook 5 min stirring often',
              'Portion into bowls, top with banana slices',
              'Drizzle peanut butter, serve immediately',
            ],
          },
          ingredients: [
            { name: 'rolled oats', amount: 2, unit: 'cups', category: 'grains' },
            { name: 'oat milk', amount: 2.5, unit: 'cups', category: 'dairy' },
            { name: 'banana', amount: 3, unit: 'whole', category: 'produce' },
            { name: 'peanut butter (natural, no salt)', amount: 4, unit: 'tbsp', category: 'pantry' },
            { name: 'cinnamon', amount: 0.5, unit: 'tsp', category: 'spices' },
            { name: 'flax seeds', amount: 2, unit: 'tbsp', category: 'pantry' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'High-protein boost for PCOS management',
              modifications: ['Add 1 scoop unflavored collagen peptides', 'Extra flax seeds for hormone support', 'Greek yogurt dollop on top'],
              safe_to_serve: true,
              nutrition_highlights: ['High protein', 'Omega-3s from flax', 'Complex carbs'],
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium, heart-healthy',
              modifications: ['Unsalted peanut butter only', 'No added salt', 'Drizzle of honey instead of sweet toppings', 'Add walnuts for heart health'],
              safe_to_serve: true,
              nutrition_highlights: ['Heart-healthy fats', 'Low sodium', 'Fiber-rich'],
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free, toddler texture, fun presentation',
              modifications: ['No eggs in recipe (naturally egg-free)', 'Slightly thicker oats for easier self-feeding', 'Banana slices as "faces" on top', 'Cooled to safe temperature'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓ (oat bowls contain no egg)'],
              nutrition_highlights: ['Iron from oats', 'Potassium from banana'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Baby-safe puree, no honey, no peanut butter (introduce gradually)',
              modifications: ['Plain oat porridge cooked with breastmilk or formula instead of oat milk', 'Mashed banana stirred in', 'NO peanut butter (introduce separately per allergy protocol)', 'NO honey', 'No salt, no sugar'],
              safe_to_serve: true,
              allergy_notes: ['No PB until cleared by pediatrician', 'No honey (botulism risk)'],
              nutrition_highlights: ['Iron-fortified oats', 'Vitamin B6 from banana'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Kid-approved, mild, satisfying',
              modifications: ['Regular portion', 'Extra banana', 'Small swirl of peanut butter on top', 'Sprinkle of mini chocolate chips as treat (Fridays)'],
              safe_to_serve: true,
              nutrition_highlights: ['Long-lasting energy', 'Kid-friendly'],
            },
          ],
        },
        {
          id: 'meal-mon-dinner',
          name: 'Sheet Pan Lemon Herb Salmon with Roasted Vegetables',
          type: 'dinner',
          cuisine_type: 'Mediterranean',
          estimated_prep_time: 15,
          estimated_cook_time: 25,
          estimated_cost: 22.5,
          servings: 5,
          calorie_estimate: 520,
          image_prompt: 'sheet pan salmon fillets with colorful roasted vegetables, lemon slices, fresh herbs, rustic kitchen backdrop',
          base_recipe: {
            description: 'Tender salmon fillets roasted alongside colorful vegetables with lemon and herbs. One pan, minimal cleanup.',
            steps: [
              'Preheat oven to 400°F (200°C)',
              'Toss broccoli, bell peppers, zucchini with olive oil on large sheet pan',
              'Season salmon with lemon zest, garlic, dill, no salt (season adults at table)',
              'Nestle salmon among vegetables',
              'Roast 20-22 minutes until salmon flakes and vegetables are caramelized',
              'Finish with fresh lemon squeeze',
            ],
          },
          ingredients: [
            { name: 'salmon fillets', amount: 5, unit: 'pieces (4oz each)', category: 'protein' },
            { name: 'broccoli florets', amount: 3, unit: 'cups', category: 'produce' },
            { name: 'bell peppers (mixed)', amount: 2, unit: 'whole', category: 'produce' },
            { name: 'zucchini', amount: 2, unit: 'whole', category: 'produce' },
            { name: 'olive oil', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'lemon', amount: 2, unit: 'whole', category: 'produce' },
            { name: 'garlic cloves', amount: 4, unit: 'whole', category: 'produce' },
            { name: 'fresh dill', amount: 1, unit: 'bunch', category: 'produce' },
            { name: 'sweet potato', amount: 2, unit: 'medium', category: 'produce' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS-optimized: anti-inflammatory boost',
              modifications: ['Full portion + extra salmon for protein', 'Add turmeric to vegetables', 'Side of quinoa for complex carbs'],
              safe_to_serve: true,
              nutrition_highlights: ['Omega-3s', 'Anti-inflammatory', 'High protein'],
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium, heart-healthy',
              modifications: ['No salt added at any stage', 'Herbs and lemon for flavor only', 'Extra vegetables for fiber'],
              safe_to_serve: true,
              nutrition_highlights: ['Heart-healthy omega-3s', 'Low sodium', 'High fiber'],
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Flaked salmon, soft-roasted veggies, no eggs anywhere (egg-free base meal ✓)',
              modifications: ['Salmon flaked into small pieces, check for bones', 'Vegetables roasted extra soft', 'Plain rice or pasta on the side', 'Skip bell pepper if reactive'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓ (no egg in this recipe)'],
              nutrition_highlights: ['DHA for brain development', 'Soft textures'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Pureed salmon and vegetables, finger-food broccoli',
              modifications: ['Puree salmon with breastmilk/formula to creamy texture', 'Steam broccoli separately (softer than roasted) as finger food', 'No lemon juice on baby portion', 'NO salt, NO spices except tiny dill'],
              safe_to_serve: true,
              allergy_notes: ['Fish is a Top 8 allergen — if first introduction, offer a small amount first'],
              nutrition_highlights: ['DHA critical for brain development', 'Iron', 'Vitamin D'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Kid-portion, mild, with rice',
              modifications: ['Salmon as fish sticks by cutting into strips before roasting', 'Extra sweet potato wedges', 'Mild flavoring only', 'Side of rice'],
              safe_to_serve: true,
              nutrition_highlights: ['DHA for learning', 'Vitamins from colorful veggies'],
            },
          ],
        },
      ],
    },
    // ── TUESDAY ───────────────────────────────────────────────
    {
      date: '2025-01-21',
      day_of_week: 1,
      meals: [
        {
          id: 'meal-tue-breakfast',
          name: 'Avocado Toast Board',
          type: 'breakfast',
          cuisine_type: 'American',
          estimated_prep_time: 10,
          estimated_cook_time: 5,
          estimated_cost: 6.8,
          servings: 5,
          calorie_estimate: 310,
          image_prompt: 'artisan avocado toast spread on wooden board with toppings in small bowls, morning light, overhead view',
          base_recipe: {
            description: 'Creamy smashed avocado on toasted sourdough with customizable toppings. A "board" setup lets each family member pick their own toppings.',
            steps: [
              'Toast sourdough slices until golden',
              'Mash avocados with lime juice in a large bowl',
              'Set out topping bowls (seeds, microgreens, tomatoes)',
              'Season adult portions at table',
              'Let everyone build their own toast',
            ],
          },
          ingredients: [
            { name: 'sourdough bread', amount: 10, unit: 'slices', category: 'grains' },
            { name: 'ripe avocados', amount: 4, unit: 'large', category: 'produce' },
            { name: 'cherry tomatoes', amount: 1, unit: 'cup', category: 'produce' },
            { name: 'lime', amount: 1, unit: 'whole', category: 'produce' },
            { name: 'hemp seeds', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'microgreens', amount: 1, unit: 'small package', category: 'produce' },
            { name: 'red pepper flakes', amount: 1, unit: 'pinch', category: 'spices' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS-friendly: protein addition',
              modifications: ['Add hemp seeds + smoked salmon for protein boost', 'Sprinkle nutritional yeast', 'Use sprouted grain bread for lower glycemic index'],
              safe_to_serve: true,
              nutrition_highlights: ['Healthy fats', 'High protein', 'Low GI'],
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium — no added salt',
              modifications: ['No salt — lemon/lime for flavor', 'Add sliced cucumber for freshness', 'Whole grain bread'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free (naturally), soft bread, deconstructed',
              modifications: ['Soft bread lightly toasted', 'Avocado served on side as "green dip"', 'Cherry tomatoes halved for safety', 'No spicy toppings'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Avocado as finger food or puree',
              modifications: ['Ripe avocado mashed or in spears for self-feeding (BLW)', 'Soft bread fingers without crust', 'NO salt', 'NO lime juice (too acidic for young babies — use sparingly)'],
              safe_to_serve: true,
              nutrition_highlights: ['Healthy fats for brain development', 'Folate', 'Vitamin K'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Fun presentation, mild toppings',
              modifications: ['Cut toast into dinosaur/fun shapes with cookie cutter', 'Cherry tomato faces', 'No spicy flakes'],
              safe_to_serve: true,
            },
          ],
        },
        {
          id: 'meal-tue-lunch',
          name: 'Chicken & Veggie Rice Bowls',
          type: 'lunch',
          cuisine_type: 'Asian-Fusion',
          estimated_prep_time: 15,
          estimated_cook_time: 25,
          estimated_cost: 12.4,
          servings: 5,
          calorie_estimate: 450,
          image_prompt: 'colorful rice bowl with grilled chicken, edamame, shredded carrots, cucumber, sesame seeds, teriyaki drizzle',
          base_recipe: {
            description: 'Grilled chicken over brown rice with rainbow vegetables and a mild teriyaki-style sauce (low sodium). Perfect for meal prep.',
            steps: [
              'Cook brown rice in rice cooker or pot',
              'Slice chicken breast, grill 6-7 min per side',
              'Prepare raw veggie toppings: shred carrots, slice cucumber, thaw edamame',
              'Make low-sodium sauce: coconut aminos + sesame oil + rice vinegar + ginger',
              'Assemble bowls, sauce on the side',
            ],
          },
          ingredients: [
            { name: 'chicken breast', amount: 1.5, unit: 'lbs', category: 'protein' },
            { name: 'brown rice', amount: 2, unit: 'cups dry', category: 'grains' },
            { name: 'edamame (frozen, shelled)', amount: 1.5, unit: 'cups', category: 'produce' },
            { name: 'carrots', amount: 3, unit: 'medium', category: 'produce' },
            { name: 'cucumber', amount: 2, unit: 'medium', category: 'produce' },
            { name: 'coconut aminos', amount: 4, unit: 'tbsp', category: 'pantry' },
            { name: 'sesame oil', amount: 1, unit: 'tbsp', category: 'pantry' },
            { name: 'rice vinegar', amount: 2, unit: 'tbsp', category: 'pantry' },
            { name: 'ginger (fresh)', amount: 1, unit: 'inch piece', category: 'produce' },
            { name: 'sesame seeds', amount: 2, unit: 'tbsp', category: 'pantry' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: extra protein, cauliflower rice option',
              modifications: ['1.5x chicken portion', 'Sub half rice with cauliflower rice', 'Add roasted chickpeas for extra protein', 'Full teriyaki sauce'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium: coconut aminos only, no soy sauce',
              modifications: ['Coconut aminos ONLY (lower sodium than soy)', 'No added salt anywhere', 'Extra cucumber and edamame'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓, deconstructed, mild sauce',
              modifications: ['Chicken cut into tiny pieces', 'Rice, chicken, veggies in separate sections', 'Very light drizzle of sauce (or skip)', 'Edamame squished out of pods'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓ — no egg in recipe'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Baby-led weaning: soft chicken strips, rice puree',
              modifications: ['Puree chicken with a little broth', 'Rice congee consistency', 'Finger food: cucumber spears, soft cooked carrot spears', 'NO sauce (sodium)'],
              safe_to_serve: true,
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'School lunch: pack in bento box',
              modifications: ['Brown rice, diced chicken, cucumber, carrots in bento sections', 'Sauce in separate container', 'Add small caprese for fun', 'Thermos with warm rice if preferred'],
              safe_to_serve: true,
            },
          ],
        },
        {
          id: 'meal-tue-dinner',
          name: 'One-Pot Turkey Lentil Veggie Soup',
          type: 'dinner',
          cuisine_type: 'American',
          estimated_prep_time: 20,
          estimated_cook_time: 40,
          estimated_cost: 14.2,
          servings: 5,
          calorie_estimate: 380,
          image_prompt: 'steaming pot of hearty lentil soup with vegetables and ground turkey, crusty bread on side, cozy kitchen',
          base_recipe: {
            description: 'Hearty one-pot soup with ground turkey, red lentils, and seasonal vegetables. Great leftover potential.',
            steps: [
              'Brown ground turkey in large pot, 8-10 min',
              'Add diced onion, celery, carrots — sauté 5 min',
              'Add garlic, cumin, coriander, turmeric — cook 1 min',
              'Add rinsed red lentils, diced tomatoes, low-sodium broth',
              'Simmer 25-30 min until lentils fall apart and soup thickens',
              'Stir in spinach, adjust seasoning for adults at table',
              'Serve with crusty bread',
            ],
          },
          ingredients: [
            { name: 'ground turkey (lean)', amount: 1, unit: 'lb', category: 'protein' },
            { name: 'red lentils', amount: 1.5, unit: 'cups', category: 'pantry' },
            { name: 'carrots', amount: 3, unit: 'medium', category: 'produce' },
            { name: 'celery stalks', amount: 3, unit: 'whole', category: 'produce' },
            { name: 'yellow onion', amount: 1, unit: 'large', category: 'produce' },
            { name: 'garlic cloves', amount: 5, unit: 'whole', category: 'produce' },
            { name: 'diced tomatoes (no-salt)', amount: 1, unit: '14oz can', category: 'pantry' },
            { name: 'low-sodium chicken broth', amount: 6, unit: 'cups', category: 'pantry' },
            { name: 'baby spinach', amount: 3, unit: 'cups', category: 'produce' },
            { name: 'cumin', amount: 1.5, unit: 'tsp', category: 'spices' },
            { name: 'turmeric', amount: 0.5, unit: 'tsp', category: 'spices' },
            { name: 'sourdough bread', amount: 1, unit: 'loaf', category: 'grains' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: extra protein, anti-inflammatory spices',
              modifications: ['Full portion with extra turkey', 'Extra turmeric for anti-inflammatory benefits', 'Drizzle of tahini for healthy fats'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Heart-healthy, low-sodium throughout',
              modifications: ['No-salt-added tomatoes and broth only', 'No salt at table', 'Lemon juice for brightness instead'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓, thickened texture, mild spices',
              modifications: ['Separate portion before adding spices', 'Blend to smooth or chunky texture', 'Serve with soft bread pieces for dipping'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Smooth lentil puree, no spices, no salt',
              modifications: ['Blend lentils and carrots with formula/breastmilk', 'No spices except tiny turmeric', 'Serve at warm (not hot) temperature', 'NO salt'],
              safe_to_serve: true,
              nutrition_highlights: ['Iron from lentils', 'Protein from turkey', 'Vitamin A from carrots'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Kid-friendly mild version, crusty bread',
              modifications: ['Mild spice level', 'Extra carrots and turkey pieces', 'Toasted bread torn into dunking pieces'],
              safe_to_serve: true,
            },
          ],
        },
      ],
    },
    // ── WEDNESDAY ─────────────────────────────────────────────
    {
      date: '2025-01-22',
      day_of_week: 2,
      meals: [
        {
          id: 'meal-wed-breakfast',
          name: 'Berry Smoothie Bowl Stations',
          type: 'breakfast',
          cuisine_type: 'American',
          estimated_prep_time: 10,
          estimated_cook_time: 0,
          estimated_cost: 5.1,
          servings: 5,
          calorie_estimate: 290,
          image_prompt: 'vibrant purple acai smoothie bowl with granola, fresh berries, sliced banana, seeds arranged artistically',
          base_recipe: {
            description: 'Thick blended berry smoothie base in bowls with a built-out toppings station. No cooking required.',
            steps: [
              'Blend frozen mixed berries + banana + oat milk until thick',
              'Pour into bowls (should be thick, not pourable)',
              'Set out topping station: granola, fresh fruit, seeds, nut butters',
              'Each person customizes their bowl',
            ],
          },
          ingredients: [
            { name: 'frozen mixed berries', amount: 4, unit: 'cups', category: 'produce' },
            { name: 'banana (frozen)', amount: 3, unit: 'whole', category: 'produce' },
            { name: 'oat milk', amount: 1.5, unit: 'cups', category: 'dairy' },
            { name: 'granola (low sugar)', amount: 2, unit: 'cups', category: 'pantry' },
            { name: 'fresh strawberries', amount: 1, unit: 'cup', category: 'produce' },
            { name: 'chia seeds', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'almond butter', amount: 4, unit: 'tbsp', category: 'pantry' },
            { name: 'shredded coconut (unsweetened)', amount: 0.5, unit: 'cup', category: 'pantry' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: protein powder, hormone-supporting seeds',
              modifications: ['Add vanilla protein powder to blend', 'Top with flax seeds + pumpkin seeds', 'Use almond butter for healthy fats'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium, heart-healthy toppings',
              modifications: ['Unsalted granola', 'Walnuts instead of almond butter', 'No added sweeteners'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓, no whole nuts, fun presentation',
              modifications: ['Thicker blend, served in suction cup bowl', 'Small granola pieces (no whole nuts)', 'Strawberries cut small', 'Nut butter spread thin on a spoon'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Plain berry puree, no toppings with choking hazard',
              modifications: ['Blend only berries + banana + formula', 'NO granola (hard + choking)', 'NO honey', 'NO nut butters until cleared', 'Serve as puree or thick smoothie in a sippy cup'],
              safe_to_serve: true,
              nutrition_highlights: ['Antioxidants', 'Vitamin C', 'Natural sugars for energy'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Fun arrangement, kid-approved',
              modifications: ['Make smiley face with berries on top', 'Extra granola crunchy layer', 'Mild flavors, no new additions'],
              safe_to_serve: true,
            },
          ],
        },
        {
          id: 'meal-wed-dinner',
          name: 'Baked Turkey Meatballs in Tomato Sauce over Pasta',
          type: 'dinner',
          cuisine_type: 'Italian',
          estimated_prep_time: 20,
          estimated_cook_time: 35,
          estimated_cost: 15.6,
          servings: 5,
          calorie_estimate: 540,
          image_prompt: 'spaghetti with turkey meatballs in rich tomato sauce, fresh basil, parmesan, white pasta bowl, Italian kitchen ambiance',
          base_recipe: {
            description: 'Oven-baked turkey meatballs in a simple no-salt tomato sauce over pasta. Egg-free meatballs for the whole family.',
            steps: [
              'Mix ground turkey + breadcrumbs + parsley + garlic powder (NO egg binder)',
              'Roll into 1-inch balls, bake at 400°F for 20 min',
              'Simmer crushed no-salt tomatoes + garlic + basil + olive oil for 20 min',
              'Cook pasta according to package (reserve pasta water)',
              'Combine meatballs in sauce, serve over pasta',
            ],
          },
          ingredients: [
            { name: 'ground turkey', amount: 1.5, unit: 'lbs', category: 'protein' },
            { name: 'breadcrumbs (plain)', amount: 0.5, unit: 'cup', category: 'pantry' },
            { name: 'garlic (minced)', amount: 6, unit: 'cloves', category: 'produce' },
            { name: 'fresh parsley', amount: 0.5, unit: 'cup', category: 'produce' },
            { name: 'no-salt crushed tomatoes', amount: 2, unit: '14oz cans', category: 'pantry' },
            { name: 'spaghetti', amount: 1, unit: 'lb', category: 'grains' },
            { name: 'fresh basil', amount: 1, unit: 'cup', category: 'produce' },
            { name: 'olive oil', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'parmesan (for adults)', amount: 0.5, unit: 'cup grated', category: 'dairy' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: zucchini noodle option, extra meatballs',
              modifications: ['Sub half pasta with spiralized zucchini', 'Extra 3 meatballs for protein', 'Full parmesan'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium: no-salt tomatoes, no parmesan',
              modifications: ['No-salt tomatoes only', 'No parmesan (high sodium)', 'Nutritional yeast as low-sodium sub'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free meatballs ✓, cut spaghetti, mild sauce',
              modifications: ['Meatballs are already egg-free ✓', 'Cut spaghetti with scissors into short pieces', 'Mild tomato sauce, no spice', 'Meatballs cut into quarters'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free meatballs ✓ (flax or breadcrumbs bind instead of egg)'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Soft pasta finger food + pureed meatball',
              modifications: ['Very soft-cooked short pasta pieces (penne cut up)', 'Meatball pureed with tomato sauce', 'No salt, no added spices', 'Serve warm not hot'],
              safe_to_serve: true,
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Kid classic — generous portion, mild',
              modifications: ['Regular pasta + 4 meatballs', 'Light parmesan sprinkle', 'Extra tomato sauce as he likes'],
              safe_to_serve: true,
            },
          ],
        },
      ],
    },
    // ── THURSDAY ──────────────────────────────────────────────
    {
      date: '2025-01-23',
      day_of_week: 3,
      meals: [
        {
          id: 'meal-thu-breakfast',
          name: 'Tropical Chia Pudding Parfaits',
          type: 'breakfast',
          cuisine_type: 'American',
          estimated_prep_time: 10,
          estimated_cook_time: 0,
          estimated_cost: 4.5,
          servings: 5,
          calorie_estimate: 280,
          image_prompt: 'layered chia seed pudding parfait with coconut milk, mango, and pineapple in glass jars, tropical morning',
          base_recipe: {
            description: 'Make-ahead chia pudding with coconut milk, layered with tropical fruits. Prep the night before for a stress-free morning.',
            steps: [
              'Night before: whisk chia seeds + coconut milk + vanilla + maple syrup',
              'Refrigerate overnight (at least 4 hours)',
              'Morning: stir pudding, layer with diced mango + pineapple',
              'Add granola or coconut flakes on top',
            ],
          },
          ingredients: [
            { name: 'chia seeds', amount: 0.75, unit: 'cup', category: 'pantry' },
            { name: 'coconut milk (canned)', amount: 2, unit: 'cups', category: 'pantry' },
            { name: 'oat milk', amount: 1, unit: 'cup', category: 'dairy' },
            { name: 'vanilla extract', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'maple syrup', amount: 2, unit: 'tbsp', category: 'pantry' },
            { name: 'mango (fresh or frozen)', amount: 2, unit: 'cups', category: 'produce' },
            { name: 'pineapple chunks', amount: 1.5, unit: 'cups', category: 'produce' },
            { name: 'shredded coconut', amount: 0.5, unit: 'cup', category: 'pantry' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: flax added, no maple syrup',
              modifications: ['Skip maple syrup, use stevia', 'Add ground flaxseed to pudding', 'Top with pumpkin seeds'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Heart-healthy, low-sodium',
              modifications: ['Low sodium naturally ✓', 'Walnuts on top', 'Light on sweetener'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓, small chia in smooth base, no large chunks',
              modifications: ['Blend pudding smooth to mask chia texture', 'Small mango pieces', 'No pineapple if acidic sensitivity'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Mango puree, no chia seeds (choking)',
              modifications: ['NO whole chia seeds (choking hazard)', 'Pureed mango as topping only', 'Coconut milk chia pudding blended smooth is OK if well-set', 'Offer in age-appropriate form'],
              safe_to_serve: true,
              allergy_notes: ['Chia seeds: monitor for any unusual reactions first time'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Fun parfait layers, kid-friendly',
              modifications: ['Build own parfait with layers', 'Extra mango', 'Granola crunch layer on top'],
              safe_to_serve: true,
            },
          ],
        },
        {
          id: 'meal-thu-dinner',
          name: 'Slow-Cooker Chicken Tikka Masala (Mild)',
          type: 'dinner',
          cuisine_type: 'Indian',
          estimated_prep_time: 20,
          estimated_cook_time: 240,
          estimated_cost: 16.8,
          servings: 5,
          calorie_estimate: 490,
          image_prompt: 'creamy orange tikka masala in white bowl with fluffy basmati rice, fresh cilantro, naan bread, warm ambiance',
          base_recipe: {
            description: 'Comfort food classic made mild and family-friendly in the slow cooker. Rich coconut milk base (dairy-free) keeps it safe for sensitive stomachs.',
            steps: [
              'Brown chicken thighs in skillet, add to slow cooker',
              'Combine: coconut milk + no-salt tomato paste + garam masala + mild paprika + turmeric + ginger + garlic',
              'Cook low 4-5 hours or high 2-3 hours',
              'Shred chicken, stir in coconut cream',
              'Serve over basmati rice with naan',
              'Add fresh cilantro + lime wedge for adults',
            ],
          },
          ingredients: [
            { name: 'chicken thighs (boneless)', amount: 1.5, unit: 'lbs', category: 'protein' },
            { name: 'coconut milk (full fat)', amount: 2, unit: 'cans', category: 'pantry' },
            { name: 'no-salt tomato paste', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'garam masala', amount: 2, unit: 'tsp', category: 'spices' },
            { name: 'mild paprika', amount: 2, unit: 'tsp', category: 'spices' },
            { name: 'turmeric', amount: 1, unit: 'tsp', category: 'spices' },
            { name: 'fresh ginger', amount: 2, unit: 'tsp grated', category: 'produce' },
            { name: 'garlic cloves', amount: 6, unit: 'whole', category: 'produce' },
            { name: 'basmati rice', amount: 2.5, unit: 'cups', category: 'grains' },
            { name: 'naan bread', amount: 5, unit: 'pieces', category: 'grains' },
            { name: 'fresh cilantro', amount: 1, unit: 'bunch', category: 'produce' },
            { name: 'lime', amount: 2, unit: 'whole', category: 'produce' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS-friendly: cauliflower rice, extra protein',
              modifications: ['Cauliflower rice instead of basmati', 'Extra chicken portion', 'Turmeric + anti-inflammatory spice forward'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium: no-salt tomato paste, no naan',
              modifications: ['No-salt tomato paste (verified)', 'Skip naan (high sodium)', 'Extra rice to fill', 'No salt added'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓, mild, shredded chicken, rice',
              modifications: ['Very mild portion — less spice', 'Extra coconut milk to dilute', 'Shredded chicken in tiny pieces', 'Plain basmati rice on side'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Pureed chicken + rice + mild sauce',
              modifications: ['Puree shredded chicken with coconut milk', 'Plain mashed basmati on side', 'Very small amount of sauce (flavorful but mild)', 'NO salt, NO spicy spices'],
              safe_to_serve: true,
              nutrition_highlights: ['Protein', 'Iron', 'Healthy fats from coconut milk'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Kid portion, mild, naan for dunking',
              modifications: ['Mild sauce', 'Naan for scooping', 'No cilantro (most kids dislike)', 'Regular rice'],
              safe_to_serve: true,
            },
          ],
        },
      ],
    },
    // ── FRIDAY ────────────────────────────────────────────────
    {
      date: '2025-01-24',
      day_of_week: 4,
      meals: [
        {
          id: 'meal-fri-breakfast',
          name: 'Savory Tofu Scramble & Sweet Potato Hash',
          type: 'breakfast',
          cuisine_type: 'American',
          estimated_prep_time: 10,
          estimated_cook_time: 20,
          estimated_cost: 7.2,
          servings: 5,
          calorie_estimate: 370,
          image_prompt: 'golden tofu scramble with sweet potato hash browns, fresh herbs, colorful bell peppers in cast iron skillet',
          base_recipe: {
            description: 'Protein-packed egg-free scramble made with firm tofu, turmeric, and nutritional yeast. Served alongside crispy sweet potato hash.',
            steps: [
              'Cube and roast sweet potato at 425°F for 20 min',
              'Crumble firm tofu into skillet, cook on medium-high',
              'Season with turmeric, garlic powder, nutritional yeast, low-sodium soy sauce',
              'Add bell peppers and spinach in last 3 minutes',
              'Serve tofu scramble alongside sweet potato hash',
            ],
          },
          ingredients: [
            { name: 'firm tofu (extra-firm)', amount: 2, unit: 'blocks (14oz each)', category: 'protein' },
            { name: 'sweet potato', amount: 3, unit: 'medium', category: 'produce' },
            { name: 'bell pepper (red)', amount: 2, unit: 'whole', category: 'produce' },
            { name: 'baby spinach', amount: 2, unit: 'cups', category: 'produce' },
            { name: 'turmeric', amount: 1, unit: 'tsp', category: 'spices' },
            { name: 'garlic powder', amount: 1, unit: 'tsp', category: 'spices' },
            { name: 'nutritional yeast', amount: 4, unit: 'tbsp', category: 'pantry' },
            { name: 'coconut aminos', amount: 2, unit: 'tbsp', category: 'pantry' },
            { name: 'olive oil', amount: 2, unit: 'tbsp', category: 'pantry' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: egg-free high protein, anti-inflammatory',
              modifications: ['Double tofu portion', 'Extra turmeric for PCOS inflammation', 'Avocado on side for healthy fats', 'Nutritional yeast for B12'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium — no added salt',
              modifications: ['Coconut aminos only (lower than soy)', 'No additional salt', 'Fresh herbs for flavor'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓ (tofu scramble is naturally egg-free), soft textures',
              modifications: ['Soft-crumbled tofu, not too dry', 'Sweet potato mashed not as hash', 'No bell pepper skins (remove or skip)', 'Very mild seasoning'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓ — tofu is egg-free'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Mashed sweet potato + soft tofu finger foods',
              modifications: ['Mashed sweet potato (no seasoning)', 'Soft tofu cubes as finger food (BLW)', 'NO salt', 'NO nutritional yeast (until confirmed OK)'],
              safe_to_serve: true,
              nutrition_highlights: ['Beta-carotene from sweet potato', 'Protein from tofu', 'Calcium'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Kid portion, sweet potato wedges, mild',
              modifications: ['Sweet potato wedges (fun shape)', 'Tofu scramble with ketchup on side (kid approved)', 'No spicy seasonings'],
              safe_to_serve: true,
            },
          ],
        },
        {
          id: 'meal-fri-dinner',
          name: 'Taco Bowl Night',
          type: 'dinner',
          cuisine_type: 'Mexican',
          estimated_prep_time: 20,
          estimated_cook_time: 20,
          estimated_cost: 17.3,
          servings: 5,
          calorie_estimate: 510,
          image_prompt: 'colorful taco bowls with seasoned ground beef, cilantro lime rice, black beans, pico de gallo, avocado, lime',
          base_recipe: {
            description: 'Interactive taco bowl night where each person builds their own bowl. Mild seasoned ground beef/turkey, rice, beans, and fresh toppings.',
            steps: [
              'Season ground turkey/beef with mild cumin, paprika, garlic powder',
              'Cook meat in skillet, drain fat',
              'Prepare cilantro lime rice',
              'Warm black beans (no-salt-added)',
              'Set up topping station: pico, avocado, lime, sour cream, shredded cheese',
              'Everyone builds their own bowl!',
            ],
          },
          ingredients: [
            { name: 'ground turkey or beef (lean)', amount: 1.5, unit: 'lbs', category: 'protein' },
            { name: 'brown rice', amount: 2, unit: 'cups dry', category: 'grains' },
            { name: 'black beans (no-salt)', amount: 2, unit: '15oz cans', category: 'pantry' },
            { name: 'tomatoes', amount: 3, unit: 'medium', category: 'produce' },
            { name: 'white onion', amount: 1, unit: 'medium', category: 'produce' },
            { name: 'cilantro', amount: 1, unit: 'bunch', category: 'produce' },
            { name: 'avocados', amount: 3, unit: 'large', category: 'produce' },
            { name: 'lime', amount: 3, unit: 'whole', category: 'produce' },
            { name: 'shredded Mexican cheese', amount: 1.5, unit: 'cups', category: 'dairy' },
            { name: 'sour cream (plain yogurt for adults)', amount: 1, unit: 'cup', category: 'dairy' },
            { name: 'cumin', amount: 2, unit: 'tsp', category: 'spices' },
            { name: 'mild paprika', amount: 1.5, unit: 'tsp', category: 'spices' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: cauliflower rice option, extra protein',
              modifications: ['Sub brown rice with cauliflower rice', 'Greek yogurt instead of sour cream', 'Extra avocado', 'Add pumpkin seeds for zinc (PCOS)'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium: no cheese, no sour cream, no salt',
              modifications: ['Skip cheese and sour cream (high sodium)', 'Extra avocado for creaminess', 'Fresh lime juice for flavor', 'No salt added to meat'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓, mild, deconstructed',
              modifications: ['Separate rice + beans + meat on plate', 'Very mild seasoning on meat', 'Avocado mashed', 'Cheese sprinkle OK', 'No onion in pico'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Pureed beans, mashed avocado, soft rice',
              modifications: ['Pureed black beans as dip/puree', 'Mashed avocado finger food', 'Plain rice (no seasoning)', 'Small amount of unseasoned meat', 'NO salt, NO spices'],
              safe_to_serve: true,
              nutrition_highlights: ['Iron from beans', 'Healthy fats from avocado', 'Protein'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'School lunch next day: pack leftover taco bowl',
              modifications: ['Regular mild taco bowl', 'Pack leftovers: rice + beans + meat in thermos for school', 'Cheese + corn chips on the side in school lunch', 'No spicy salsa'],
              safe_to_serve: true,
            },
          ],
        },
      ],
    },
    // ── SATURDAY ──────────────────────────────────────────────
    {
      date: '2025-01-25',
      day_of_week: 5,
      meals: [
        {
          id: 'meal-sat-breakfast',
          name: 'Fluffy Egg-Free Pancakes with Berry Compote',
          type: 'breakfast',
          cuisine_type: 'American',
          estimated_prep_time: 10,
          estimated_cook_time: 20,
          estimated_cost: 5.8,
          servings: 5,
          calorie_estimate: 390,
          image_prompt: 'stack of golden fluffy pancakes with fresh berry compote, maple syrup, butter, weekend breakfast table setting',
          base_recipe: {
            description: 'Weekend pancake tradition! These egg-free pancakes use flax eggs and are fluffy and delicious for the whole family.',
            steps: [
              'Mix flax egg (2 tbsp ground flax + 6 tbsp water, sit 5 min)',
              'Whisk flour + baking powder + salt (skip salt for Sam/Ava portions)',
              'Add oat milk + vanilla + melted coconut oil + flax egg',
              'Cook on medium griddle, flip when bubbles form',
              'Simmer berries + maple syrup for compote',
            ],
          },
          ingredients: [
            { name: 'all-purpose flour', amount: 2, unit: 'cups', category: 'pantry' },
            { name: 'ground flaxseed', amount: 4, unit: 'tbsp', category: 'pantry' },
            { name: 'baking powder', amount: 2, unit: 'tsp', category: 'pantry' },
            { name: 'oat milk', amount: 2, unit: 'cups', category: 'dairy' },
            { name: 'vanilla extract', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'coconut oil', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'mixed berries (fresh or frozen)', amount: 2, unit: 'cups', category: 'produce' },
            { name: 'maple syrup', amount: 0.25, unit: 'cup', category: 'pantry' },
            { name: 'banana', amount: 2, unit: 'whole', category: 'produce' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: protein-boosted, lower glycemic',
              modifications: ['Protein powder in batter', 'Sub half flour with almond flour', 'Skip maple syrup — berries only', 'Add hemp seeds to batter'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium: no baking powder salt, just berries',
              modifications: ['Use low-sodium baking powder', 'No added salt in batter', 'Fresh berries only (no extra maple)'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓ (flax eggs), fun shapes, mild',
              modifications: ['These pancakes are egg-free! ✓', 'Use fun cookie cutter shapes (star, dinosaur)', 'Serve with mashed banana instead of compote', 'Small bite-sized pieces'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓ — flax eggs used as binder'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Mini pancake finger foods, no honey, no maple',
              modifications: ['Mini silver-dollar pancakes (BLW finger food)', 'NO honey', 'NO maple syrup (wait until 12mo)', 'Plain or with mashed banana', 'NO salt in Ava\'s batter portion'],
              safe_to_serve: true,
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Classic stack, berry compote, maple syrup',
              modifications: ['Stack of 3-4 pancakes', 'Berry compote + maple syrup', 'Add chocolate chip eyes + banana mouth on top pancake for fun'],
              safe_to_serve: true,
            },
          ],
        },
        {
          id: 'meal-sat-dinner',
          name: 'Herb-Roasted Whole Chicken with Root Vegetable Medley',
          type: 'dinner',
          cuisine_type: 'American',
          estimated_prep_time: 20,
          estimated_cook_time: 90,
          estimated_cost: 24.0,
          servings: 5,
          calorie_estimate: 580,
          image_prompt: 'golden roasted whole chicken surrounded by colorful root vegetables, rosemary sprigs, rustic cast iron, Sunday dinner feeling',
          base_recipe: {
            description: 'Sunday-style roast chicken (on Saturday!) with minimal seasoning so every family member can enjoy. Yields leftover chicken for the week.',
            steps: [
              'Pat chicken dry, rub with olive oil, garlic, rosemary (no salt)',
              'Stuff cavity with lemon halves and garlic',
              'Toss root vegetables (parsnips, carrots, sweet potato, beets) with olive oil',
              'Roast chicken at 400°F 1 hr 15 min (165°F internal)',
              'Rest chicken 10 min before carving',
              'Salt adult portions at table',
            ],
          },
          ingredients: [
            { name: 'whole chicken (3-4 lbs)', amount: 1, unit: 'whole', category: 'protein' },
            { name: 'carrots', amount: 4, unit: 'medium', category: 'produce' },
            { name: 'parsnips', amount: 3, unit: 'medium', category: 'produce' },
            { name: 'sweet potato', amount: 2, unit: 'large', category: 'produce' },
            { name: 'beets', amount: 2, unit: 'medium', category: 'produce' },
            { name: 'garlic head', amount: 1, unit: 'whole', category: 'produce' },
            { name: 'rosemary (fresh)', amount: 3, unit: 'sprigs', category: 'produce' },
            { name: 'lemon', amount: 2, unit: 'whole', category: 'produce' },
            { name: 'olive oil', amount: 4, unit: 'tbsp', category: 'pantry' },
            { name: 'thyme (fresh)', amount: 3, unit: 'sprigs', category: 'produce' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: breast meat, anti-inflammatory veg',
              modifications: ['White breast meat (leaner for PCOS)', 'Extra sweet potato and beets (blood sugar regulation)', 'Lemon and herb focus'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium: no salt on chicken, herbs only',
              modifications: ['No salt added', 'Rosemary + garlic + lemon for flavor', 'Skip any gravy (sodium)'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓, tender dark meat, soft veg',
              modifications: ['Tender thigh/leg meat (easier to chew)', 'Vegetables roasted until very soft', 'No seasoning on Leo\'s portion', 'Shredded chicken is easiest'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Pureed chicken + sweet potato, no seasoning',
              modifications: ['Puree: shredded chicken breast + sweet potato + broth', 'NO salt, NO herbs in puree', 'Carrot spears for self-feeding (BLW)', 'Ensure all bones removed'],
              safe_to_serve: true,
              nutrition_highlights: ['Complete protein', 'Vitamin A', 'Iron from dark meat'],
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Drumstick tradition, sweet potato, mild',
              modifications: ['Drumstick or wing for fun', 'Sweet potato wedges', 'Light herbs', 'Save leftovers for chicken sandwiches tomorrow'],
              safe_to_serve: true,
            },
          ],
        },
      ],
    },
    // ── SUNDAY ────────────────────────────────────────────────
    {
      date: '2025-01-26',
      day_of_week: 6,
      meals: [
        {
          id: 'meal-sun-breakfast',
          name: 'French Toast Casserole (Egg-Free)',
          type: 'breakfast',
          cuisine_type: 'American',
          estimated_prep_time: 15,
          estimated_cook_time: 35,
          estimated_cost: 6.5,
          servings: 5,
          calorie_estimate: 420,
          image_prompt: 'golden baked french toast casserole in white baking dish with powdered sugar, berries, maple syrup, Sunday morning',
          base_recipe: {
            description: 'Baked cinnamon french toast casserole using aquafaba (chickpea liquid) as egg-free substitute. Prep the night before, bake in the morning.',
            steps: [
              'Night before: whisk aquafaba + oat milk + cinnamon + vanilla + maple syrup',
              'Cube day-old sourdough bread, arrange in greased baking dish',
              'Pour mixture over bread, press down, refrigerate overnight',
              'Next morning: bake at 375°F for 30-35 min until golden and set',
              'Top with fresh berries and light maple syrup',
            ],
          },
          ingredients: [
            { name: 'sourdough bread (day old)', amount: 1, unit: 'loaf', category: 'grains' },
            { name: 'aquafaba (canned chickpea liquid)', amount: 0.75, unit: 'cup', category: 'pantry' },
            { name: 'oat milk', amount: 2, unit: 'cups', category: 'dairy' },
            { name: 'cinnamon', amount: 2, unit: 'tsp', category: 'spices' },
            { name: 'vanilla extract', amount: 1.5, unit: 'tsp', category: 'pantry' },
            { name: 'maple syrup', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'mixed berries', amount: 2, unit: 'cups', category: 'produce' },
            { name: 'powdered sugar (for dusting)', amount: 2, unit: 'tbsp', category: 'pantry' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: higher protein version, no maple syrup',
              modifications: ['Add vanilla protein powder to custard mix', 'Skip maple syrup', 'Top with Greek yogurt instead of powdered sugar'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium: no salt in recipe (naturally low)',
              modifications: ['Naturally low sodium ✓', 'Light portion of maple syrup', 'Fresh berries only'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓ (aquafaba is egg-free), soft, cut small',
              modifications: ['Egg-free using aquafaba ✓', 'Soft center pieces (skip crispy edges)', 'Cut into small squares', 'Berries on side, not on top'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓ — aquafaba replaces egg'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Soft bread fingers, no maple syrup, no powder',
              modifications: ['Soft baked bread pieces as finger food (BLW)', 'NO maple syrup or sugar', 'No powdered sugar', 'Plain with mashed banana on side'],
              safe_to_serve: true,
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Classic weekend treat, full toppings',
              modifications: ['Generous portion with maple syrup', 'Powdered sugar dusting', 'Berries on top', 'Extra piece for growing boy'],
              safe_to_serve: true,
            },
          ],
        },
        {
          id: 'meal-sun-dinner',
          name: 'Leftover Roast Chicken Fried Rice',
          type: 'dinner',
          cuisine_type: 'Asian-Fusion',
          estimated_prep_time: 15,
          estimated_cook_time: 15,
          estimated_cost: 5.0,
          servings: 5,
          calorie_estimate: 420,
          image_prompt: 'colorful fried rice in wok with shredded chicken, peas, carrots, egg-free, sesame seeds, green onions, steam rising',
          base_recipe: {
            description: 'Zero-waste Sunday dinner using Saturday\'s leftover roast chicken. Egg-free fried rice with lots of vegetables.',
            steps: [
              'Day-old rice works best (cold from fridge)',
              'Heat large wok or skillet on high heat',
              'Fry garlic + ginger + green onion 30 sec',
              'Add cold rice, press and stir fry 3-4 min',
              'Add shredded leftover chicken',
              'Add frozen peas + corn + carrots',
              'Season with coconut aminos + sesame oil',
              'Garnish with green onion + sesame seeds',
            ],
          },
          ingredients: [
            { name: 'cooked brown rice (day-old)', amount: 4, unit: 'cups', category: 'grains' },
            { name: 'leftover roast chicken (shredded)', amount: 2, unit: 'cups', category: 'protein' },
            { name: 'frozen peas', amount: 1, unit: 'cup', category: 'produce' },
            { name: 'frozen corn', amount: 1, unit: 'cup', category: 'produce' },
            { name: 'carrots (diced)', amount: 2, unit: 'medium', category: 'produce' },
            { name: 'green onions', amount: 4, unit: 'stalks', category: 'produce' },
            { name: 'garlic cloves', amount: 4, unit: 'whole', category: 'produce' },
            { name: 'fresh ginger', amount: 1, unit: 'tsp grated', category: 'produce' },
            { name: 'coconut aminos', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'sesame oil', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'sesame seeds', amount: 2, unit: 'tbsp', category: 'pantry' },
          ],
          member_variations: [
            {
              member_id: 'maya',
              member_name: 'Maya',
              life_stage: 'adult',
              modification_summary: 'PCOS: extra chicken, cauliflower rice mix',
              modifications: ['Mix cauliflower rice with brown rice', 'Extra chicken', 'Add edamame for more protein'],
              safe_to_serve: true,
            },
            {
              member_id: 'sam',
              member_name: 'Sam',
              life_stage: 'adult',
              modification_summary: 'Low-sodium: coconut aminos only',
              modifications: ['Coconut aminos only (no soy sauce)', 'No added salt', 'Extra vegetables'],
              safe_to_serve: true,
            },
            {
              member_id: 'leo',
              member_name: 'Leo',
              life_stage: 'toddler',
              modification_summary: 'Egg-free ✓, mild, soft rice, small chicken pieces',
              modifications: ['Naturally egg-free ✓', 'Plain portion before adding sauces', 'Peas and corn as fun finger foods', 'Soft rice consistency'],
              safe_to_serve: true,
              allergy_notes: ['Egg-free ✓ — no egg added to this dish'],
            },
            {
              member_id: 'ava',
              member_name: 'Ava',
              life_stage: 'baby',
              modification_summary: 'Pureed rice + chicken + peas, no sauce',
              modifications: ['Puree shredded chicken + rice + peas + corn with broth', 'NO sauce (sodium)', 'Soft peas as finger food', 'Serve warm'],
              safe_to_serve: true,
            },
            {
              member_id: 'noah',
              member_name: 'Noah',
              life_stage: 'kid',
              modification_summary: 'Kid-approved fried rice, full portion',
              modifications: ['Full portion', 'Extra sesame seeds', 'Green onions are optional', 'Pack any leftovers for Monday school lunch'],
              safe_to_serve: true,
            },
          ],
        },
      ],
    },
  ],

  // ── Weekly Grocery List ────────────────────────────────────
  grocery_list: [
    // Produce
    { id: 'g1', name: 'Bananas', category: 'produce', amount: 8, unit: 'pieces', estimated_cost: 1.5, priority: 'high', reuses_across_meals: 3 },
    { id: 'g2', name: 'Avocados (ripe)', category: 'produce', amount: 7, unit: 'whole', estimated_cost: 8.4, priority: 'high', reuses_across_meals: 3 },
    { id: 'g3', name: 'Mixed Berries (fresh)', category: 'produce', amount: 4, unit: 'cups', estimated_cost: 9.0, priority: 'high', reuses_across_meals: 4 },
    { id: 'g4', name: 'Frozen Mixed Berries', category: 'frozen', amount: 6, unit: 'cups', estimated_cost: 7.5, priority: 'high', reuses_across_meals: 3 },
    { id: 'g5', name: 'Broccoli', category: 'produce', amount: 3, unit: 'cups', estimated_cost: 2.5, priority: 'medium', reuses_across_meals: 2 },
    { id: 'g6', name: 'Bell Peppers (mixed)', category: 'produce', amount: 6, unit: 'whole', estimated_cost: 6.0, priority: 'medium', reuses_across_meals: 3 },
    { id: 'g7', name: 'Zucchini', category: 'produce', amount: 4, unit: 'whole', estimated_cost: 3.0, priority: 'medium', reuses_across_meals: 2 },
    { id: 'g8', name: 'Carrots', category: 'produce', amount: 12, unit: 'medium', estimated_cost: 3.5, priority: 'high', reuses_across_meals: 5 },
    { id: 'g9', name: 'Sweet Potatoes', category: 'produce', amount: 7, unit: 'medium', estimated_cost: 5.6, priority: 'high', reuses_across_meals: 4 },
    { id: 'g10', name: 'Lemons', category: 'produce', amount: 6, unit: 'whole', estimated_cost: 3.0, priority: 'medium', reuses_across_meals: 4 },
    { id: 'g11', name: 'Limes', category: 'produce', amount: 5, unit: 'whole', estimated_cost: 2.5, priority: 'medium', reuses_across_meals: 3 },
    { id: 'g12', name: 'Garlic (head)', category: 'produce', amount: 3, unit: 'heads', estimated_cost: 2.0, priority: 'high', reuses_across_meals: 6 },
    { id: 'g13', name: 'Fresh Ginger', category: 'produce', amount: 1, unit: 'piece', estimated_cost: 1.0, priority: 'medium', reuses_across_meals: 3 },
    { id: 'g14', name: 'Baby Spinach', category: 'produce', amount: 5, unit: 'cups', estimated_cost: 4.0, priority: 'medium', reuses_across_meals: 3 },
    { id: 'g15', name: 'Cherry Tomatoes', category: 'produce', amount: 2, unit: 'cups', estimated_cost: 3.5, priority: 'medium', reuses_across_meals: 2 },
    { id: 'g16', name: 'Cucumber', category: 'produce', amount: 4, unit: 'medium', estimated_cost: 3.0, priority: 'medium', reuses_across_meals: 2 },
    { id: 'g17', name: 'Mango (fresh or frozen)', category: 'produce', amount: 2, unit: 'cups', estimated_cost: 4.0, priority: 'low', reuses_across_meals: 1 },
    { id: 'g18', name: 'Fresh Cilantro', category: 'produce', amount: 2, unit: 'bunches', estimated_cost: 2.0, priority: 'medium', reuses_across_meals: 3 },
    { id: 'g19', name: 'Fresh Dill', category: 'produce', amount: 1, unit: 'bunch', estimated_cost: 1.5, priority: 'medium', reuses_across_meals: 1 },
    { id: 'g20', name: 'Green Onions', category: 'produce', amount: 8, unit: 'stalks', estimated_cost: 1.5, priority: 'medium', reuses_across_meals: 2 },
    // Proteins
    { id: 'g21', name: 'Salmon Fillets (4oz each)', category: 'protein', amount: 5, unit: 'pieces', estimated_cost: 18.0, priority: 'high', reuses_across_meals: 1 },
    { id: 'g22', name: 'Chicken Breast', category: 'protein', amount: 1.5, unit: 'lbs', estimated_cost: 6.0, priority: 'high', reuses_across_meals: 2 },
    { id: 'g23', name: 'Chicken Thighs (boneless)', category: 'protein', amount: 1.5, unit: 'lbs', estimated_cost: 5.5, priority: 'high', reuses_across_meals: 1 },
    { id: 'g24', name: 'Whole Chicken (3-4 lbs)', category: 'protein', amount: 1, unit: 'whole', estimated_cost: 14.0, priority: 'high', reuses_across_meals: 2 },
    { id: 'g25', name: 'Ground Turkey (lean)', category: 'protein', amount: 4, unit: 'lbs', estimated_cost: 16.0, priority: 'high', reuses_across_meals: 3 },
    { id: 'g26', name: 'Firm Tofu (extra-firm)', category: 'protein', amount: 2, unit: 'blocks', estimated_cost: 5.0, priority: 'medium', reuses_across_meals: 1 },
    // Grains
    { id: 'g27', name: 'Rolled Oats', category: 'grains', amount: 2, unit: 'cups', estimated_cost: 2.0, priority: 'high', reuses_across_meals: 2 },
    { id: 'g28', name: 'Sourdough Bread', category: 'grains', amount: 2, unit: 'loaves', estimated_cost: 9.0, priority: 'high', reuses_across_meals: 3 },
    { id: 'g29', name: 'Brown Rice', category: 'grains', amount: 4, unit: 'cups dry', estimated_cost: 3.5, priority: 'high', reuses_across_meals: 3 },
    { id: 'g30', name: 'Spaghetti', category: 'grains', amount: 1, unit: 'lb', estimated_cost: 2.5, priority: 'medium', reuses_across_meals: 1 },
    { id: 'g31', name: 'Basmati Rice', category: 'grains', amount: 2.5, unit: 'cups', estimated_cost: 3.0, priority: 'medium', reuses_across_meals: 1 },
    { id: 'g32', name: 'Naan Bread', category: 'grains', amount: 5, unit: 'pieces', estimated_cost: 4.5, priority: 'low', reuses_across_meals: 1 },
    { id: 'g33', name: 'All-Purpose Flour', category: 'pantry', amount: 2, unit: 'cups', estimated_cost: 1.5, priority: 'medium', reuses_across_meals: 1 },
    // Dairy/Alt
    { id: 'g34', name: 'Oat Milk', category: 'dairy', amount: 3, unit: 'cartons', estimated_cost: 12.0, priority: 'high', reuses_across_meals: 5 },
    { id: 'g35', name: 'Coconut Milk (full fat, canned)', category: 'pantry', amount: 4, unit: 'cans', estimated_cost: 8.0, priority: 'high', reuses_across_meals: 3 },
    { id: 'g36', name: 'Shredded Mexican Cheese', category: 'dairy', amount: 1.5, unit: 'cups', estimated_cost: 4.0, priority: 'low', reuses_across_meals: 1 },
    // Pantry
    { id: 'g37', name: 'Red Lentils', category: 'pantry', amount: 1.5, unit: 'cups', estimated_cost: 2.5, priority: 'medium', reuses_across_meals: 1 },
    { id: 'g38', name: 'Black Beans (no-salt, canned)', category: 'pantry', amount: 2, unit: 'cans', estimated_cost: 3.0, priority: 'medium', reuses_across_meals: 2 },
    { id: 'g39', name: 'Chickpeas / Aquafaba (canned)', category: 'pantry', amount: 2, unit: 'cans', estimated_cost: 2.5, priority: 'medium', reuses_across_meals: 1 },
    { id: 'g40', name: 'Coconut Aminos', category: 'pantry', amount: 1, unit: 'bottle', estimated_cost: 6.0, priority: 'high', reuses_across_meals: 4 },
    { id: 'g41', name: 'Low-Sodium Chicken Broth', category: 'pantry', amount: 6, unit: 'cups', estimated_cost: 3.5, priority: 'medium', reuses_across_meals: 2 },
    { id: 'g42', name: 'No-Salt Diced Tomatoes (canned)', category: 'pantry', amount: 1, unit: 'can', estimated_cost: 1.5, priority: 'medium', reuses_across_meals: 2 },
    { id: 'g43', name: 'No-Salt Crushed Tomatoes (canned)', category: 'pantry', amount: 2, unit: 'cans', estimated_cost: 3.0, priority: 'medium', reuses_across_meals: 1 },
    { id: 'g44', name: 'Natural Peanut Butter (no salt)', category: 'pantry', amount: 1, unit: 'jar', estimated_cost: 6.0, priority: 'high', reuses_across_meals: 2 },
    { id: 'g45', name: 'Chia Seeds', category: 'pantry', amount: 0.75, unit: 'cup', estimated_cost: 4.0, priority: 'medium', reuses_across_meals: 2 },
    { id: 'g46', name: 'Ground Flaxseed', category: 'pantry', amount: 0.5, unit: 'cup', estimated_cost: 3.0, priority: 'medium', reuses_across_meals: 3 },
    { id: 'g47', name: 'Maple Syrup', category: 'pantry', amount: 1, unit: 'bottle', estimated_cost: 7.0, priority: 'medium', reuses_across_meals: 3 },
    { id: 'g48', name: 'Olive Oil', category: 'pantry', amount: 1, unit: 'bottle', estimated_cost: 8.0, priority: 'high', reuses_across_meals: 5 },
  ],
} as unknown as AIGeneratedPlan);

// ── Demo Household ─────────────────────────────────────────

export const DEMO_HOUSEHOLD = {
  id: 'demo-household',
  user_id: 'demo-user',
  name: 'The Garcia-Chen Family',
  budget_level: 'moderate' as const,
  cooking_time_preference: '30-45 min' as const,
  meals_per_day: 3,
  cuisine_preferences: ['Mediterranean', 'Mexican', 'Asian-Fusion', 'American'],
  preferred_proteins: ['chicken', 'turkey', 'salmon', 'tofu'],
  low_energy_mode: false,
  one_pot_preference: false,
  leftovers_preference: true,
  created_at: '2025-01-01T00:00:00Z',
  updated_at: '2025-01-01T00:00:00Z',
};

export const DEMO_MEMBERS = [
  {
    id: 'maya',
    household_id: 'demo-household',
    name: 'Maya',
    stage: 'adult' as const,
    age: 34,
    picky_eater: false,
    texture_needs: null,
    school_lunch_needed: false,
    cuisine_preference: ['Mediterranean', 'Indian'],
    disliked_foods: [],
    allergies: [],
    conditions: [{ condition: 'pcos' }, { condition: 'insulin_resistance' }],
  },
  {
    id: 'sam',
    household_id: 'demo-household',
    name: 'Sam',
    stage: 'adult' as const,
    age: 37,
    picky_eater: false,
    texture_needs: null,
    school_lunch_needed: false,
    cuisine_preference: ['Asian-Fusion', 'American'],
    disliked_foods: ['cilantro'],
    allergies: [],
    conditions: [{ condition: 'hypertension' }],
  },
  {
    id: 'leo',
    household_id: 'demo-household',
    name: 'Leo',
    stage: 'toddler' as const,
    age: 3,
    picky_eater: true,
    texture_needs: 'soft',
    school_lunch_needed: false,
    cuisine_preference: [],
    disliked_foods: ['spicy food', 'onions'],
    allergies: [{ allergy: 'eggs' }],
    conditions: [],
  },
  {
    id: 'ava',
    household_id: 'demo-household',
    name: 'Ava',
    stage: 'baby' as const,
    age: null,
    picky_eater: false,
    texture_needs: 'puree',
    school_lunch_needed: false,
    cuisine_preference: [],
    disliked_foods: [],
    allergies: [],
    conditions: [],
  },
  {
    id: 'noah',
    household_id: 'demo-household',
    name: 'Noah',
    stage: 'kid' as const,
    age: 8,
    picky_eater: false,
    texture_needs: null,
    school_lunch_needed: true,
    cuisine_preference: ['American', 'Mexican'],
    disliked_foods: ['spicy food', 'mushrooms'],
    allergies: [],
    conditions: [],
  },
];
